#!/usr/bin/env bash
#
# Helm-installs Vcluster.
#

config=$1

CHART_VER=0.30.4

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)

url=https://charts.loft.sh/charts/vcluster-$CHART_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

node_ips=$(kubectl --kubeconfig $admin_kubeconfig get nodes\
  -o jsonpath={.items[*].status.addresses[?\(@.type==\"InternalIP\"\)].address}\
  | sed 's/ /,/g')

cat <<EOF >| $script_dir/values.yaml
syncer:
  extraArgs:
  - --tls-san=$node_ips
vcluster:
  image: rancher/k3s:v1.29.1-k3s2
EOF

helm upgrade --install vcluster $tgz\
  --namespace vcluster\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  --wait

# TODO ingress: false
#kubectl --kubeconfig $admin_kubeconfig -n vcluster apply -f $script_dir/ingress.yaml
kubectl --kubeconfig $admin_kubeconfig -n vcluster apply -f $script_dir/nodeport-svc.yaml
