config:
  baseURL: /headlamp

httpRoute:
  enabled: true
  labels:
    app.kubernetes.io/component: ingress
  parentRefs:
    - name: dtk-gateway
      namespace: nginx-gateway
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: headlamp
          port: 80
          weight: 1
      filters:
        - requestHeaderModifier:
            add:
              - name: Authorization
                value: "Bearer 18bb628a-9f6c-4cc6-aae3-3bf15a89ff62" 
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /headlamp/
    - filters:
        - requestRedirect:
            path:
              replaceFullPath: /headlamp/
              type: ReplaceFullPath
            statusCode: 301
          type: RequestRedirect
      matches:
        - path:
            type: Exact
            value: /headlamp
