apiVersion: v1
kind: Pod
metadata:
  annotations:
    etcd.k3s.io/initial: '{"initial-advertise-peer-urls":"https://192.168.0.24:2380","initial-cluster":"rke1-36ae2197=https://192.168.0.24:2380","initial-cluster-state":"new"}'
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
  uid: 36bf324bfd361ad521c380255e38c616
spec:
  containers:
  - command:
    - etcd
    - --config-file=/var/lib/rancher/rke2/server/db/etcd/config
    env:
    - name: FILE_HASH
      value: 68a67ac53efbe3715380ff9321287fd99e0da40dd4ca0080bb4b7e32552bf935
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    image: index.docker.io/rancher/hardened-etcd:v3.5.4-k3s1-build20220504
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    securityContext:
      privileged: false
    volumeMounts:
    - mountPath: /var/lib/rancher/rke2/server/db/etcd
      name: dir0
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      name: file0
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      name: file1
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      name: file2
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      name: file3
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      name: file4
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      name: file5
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/db/etcd/config
      name: file6
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd
      type: DirectoryOrCreate
    name: dir0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      type: File
    name: file0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      type: File
    name: file1
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      type: File
    name: file2
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      type: File
    name: file3
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      type: File
    name: file4
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      type: File
    name: file5
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd/config
      type: File
    name: file6
status: {}
