apiVersion: v1
kind: Pod
metadata:
  name: kafkactl
  namespace: kafka
spec:
  containers:
    - name: main
      image: deviceinsight/kafkactl:v1.16.0
      command:
        - sh
        - -c
        - tail -f /dev/null
      volumeMounts:
        - name: config
          mountPath: /home/kafkactl/.config/kafkactl
  volumes:
    - name: config
      configMap:
        name: kafkactl-config
