apiVersion: v1
kind: ConfigMap
metadata:
  name: kafkactl-config
  namespace: kafka
data:
  config.yml: |
    contexts:
      #default:
      #  brokers:
      #  - my-cluster-kafka-bootstrap:9092
      remote-cluster:
        brokers:
        - my-cluster-kafka-bootstrap:9092

        ## optional: tls config
        #tls:
        #  enabled: true
        #  ca: my-ca
        #  cert: my-cert
        #  certKey: my-key
        #  # set insecure to true to ignore all tls verification (defaults to false)
        #  insecure: false

        ## optional: sasl support
        #sasl:
        #  enabled: true
        #  username: admin
        #  password: admin
        #  # optional configure sasl mechanism as plaintext, scram-sha256, scram-sha512 (defaults to plaintext)
        #  mechanism: scram-sha512

        ## optional: access clusters running kubernetes
        #kubernetes:
        #  enabled: false
        #  binary: kubectl #optional
        #  kubeConfig: ~/.kube/config #optional
        #  kubeContext: my-cluster
        #  namespace: my-namespace

        ## optional: clientID config (defaults to kafkactl-{username})
        #clientID: my-client-id

        ## optional: kafkaVersion (defaults to 2.0.0)
        #kafkaVersion: 1.1.1

        ## optional: timeout for admin requests (defaults to 3s)
        #requestTimeout: 10s

        ## optional: avro schema registry
        #avro:
        #  schemaRegistry: localhost:8081

        ## optional: changes the default partitioner
        #defaultPartitioner: "hash"
    current-context: remote-cluster