virt: kvm
addons:
  - name: calico
    enabled: false
  - name: cilium
    enabled: true
  - name: coredns
    enabled: true
  - name: ingress-nginx
    enabled: true
    ssl-passthrough: false
  - name: cert-manager
    enabled: true
  - name: external-dns
    enabled: false
  - name: kube-prometheus-stack
    enabled: true
  - name: kubernetes-dashboard
    enabled: true
  - name: metrics-server
    enabled: true
  - name: openebs
    enabled: true
k8s:
  containerized-cplane:
  cluster-cidr: 10.200.0.0/16
  cluster-dns: 10.32.0.10
  kube-proxy: false
  containerd-mirror:
    enabled: false
    name: _default
    config: |
      [host."http://192.168.0.49:8080"]
        capabilities = ["pull", "resolve"]
        skip_verify = true
kvm:
  network: nat
  kickstart: kvm.text.ks.cfg
  os-variant: almalinux9
vbox:
  host-network-interface:
  host-only-network: 192.168.56
  kickstart: vbox.text.ks.cfg
  vboxdir:
vm:
  linux: alma9
  create-template: true
  template-vmname: alma9
dns:
  domain: dtk.io
  host-ip:
  webhook-port: 5000
vms:
  - name: vm1
    cpu: 3
    mem: 8192
    ip: 200
    disk:
    pod-cidr: 10.200.0.0/24
  - name: vm2
    cpu: 3
    mem: 8192
    ip: 201
    disk:
    pod-cidr: 10.200.1.0/24
  - name: vm3
    cpu: 3
    mem: 8192
    ip: 202
    disk:
    pod-cidr: 10.200.2.0/24
cluster:
