# for help see the README
virt: virtualbox
addons:
  #- calico
  - cilium
  - coredns
  - openebs
  - metrics-server
  - kube-prometheus-stack
  - kubernetes-dashboard
  - ingress-nginx
k8s:
  containerized-cplane:
  cluster-cidr: 10.200.0.0/16
  cluster-dns: 10.32.0.10
  kube-proxy: false
  containerd-mirror:
vbox:
  host-network-interface:
  host-only-network: 192.168.56
  vboxdir:
vm:
  linux: centos8
  create-template: true
  template-vmname: centos8
  kickstart: ks.text.cfg
vms:
  - name: vm1
    cpu: 3
    mem: 8192
    ip: 200
    pod-cidr: 10.200.0.0/24
  - name: vm2
    cpu: 3
    mem: 8192
    ip: 201
    pod-cidr: 10.200.1.0/24
    # - name: vm3
    #   cpu: 3
    #   mem: 8192
    #   ip: 202
    #   pod-cidr: 10.200.2.0/24
cluster:
