#!/usr/bin/env bash
#
# Desktop Kubernetes CLI.
#

set -e

long_opts=config:,create-template:,create-vms:,addon:

export DTKBASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# set from the command line by parse_cmdline function (defaults are hard-coded)
operation=
config=$DTKBASE/config.yaml
create_template=
create_vms=1
addon=

# set from config.yaml by scripts/helpers/parse-config.py
virt=
k8s_containerized_cplane=
k8s_cluster_cidr=
k8s_cluster_dns=
k8s_kube_proxy=
kvm_network=
kvm_kickstart=
kvm_os_variant=
vbox_host_network_interface=
vbox_host_only_network=
vbox_kickstart=
vbox_vboxdir=
vm_linux=
vm_create_template=
vm_template_vmname=

#
# Enables scripts to exec other scripts by name only or pathpart/name.
#
function xec() {
  if echo $1 | grep -q /; then
    f=$(find $DTKBASE/scripts -type d -name $(dirname $1) | xargs -I% find % -type f -name $(basename $1))
  else
    f=$(find $DTKBASE/scripts -name $1)
  fi
  [[ -n $f ]] && $f "${@:2}"
}

#
# Translates "true" to 1 and "false" to 0. The function arg is a variable
# name, whose contents may be modified by the function. Returns a non-zero
# exit code on error, else a zero exit code.
#
function xlat_tf() {
    local -n var_ref=$1
    if [[ -z "$var_ref" ]] || [[ $var_ref -eq 1 ]] || [[ $var_ref -eq 0 ]] then
      return
    elif [[ $var_ref == "true" ]]; then
      var_ref=1
    elif [[ $var_ref == "false" ]]; then
      var_ref=0
    else
      false
      return
    fi
    true
}

#
# Verifies the dirname pased in $1 matches a directory name under
# scripts/addons.
#
function validate_addon() {
  while read dirname; do
    if [[ $1 == $dirname ]]; then
      true
      return
    fi
  done < <(find $DTKBASE/scripts/addons -maxdepth 1 -mindepth 1 -type d -printf "%f\n")
  false
}

#
# Parses the command line.
#
function parse_cmdline() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args specified, try: ./dtk help"
    exit 1
  fi

  parse_error=
  for ((i=1; i<=$#; i++)); do
    arg="${!i}"
    case $arg in
      cluster|verify)
        ((i++))
        if [[ -z "${!i}" ]]; then
          parse_error=1
          break
        fi
        operation="$arg-${!i}"
        ;;
      install-addon)
        ((i++))
        if [[ -z "${!i}" ]]; then
          parse_error=1
          break
        fi
        operation="$arg"
        addon="${!i}"
        ;;
      check-tools)
        operation="$arg"
        ;;
      --config=*)
        config=$(echo $arg | cut -d= -f2)
        ;;
      --config)
        ((i++))
        if [[ -z "${!i}" ]]; then
          parse_error=1
          break
        fi
        config="${!i}"
        ;;
      --create-template=*)
        create_template=$(echo $arg | cut -d= -f2)
        ;;
      --create-template)
        ((i++))
        if [[ -z "${!i}" ]]; then
          parse_error=1
          break
        fi
        create_template="${!i}"
        ;;
      --create-vms=*)
        create_vms=$(echo $arg | cut -d= -f2)
        ;;
      --create-vms)
        ((i++))
        if [[ -z "${!i}" ]]; then
          parse_error=1
          break
        fi
        create_vms="${!i}"
        ;;
      help|--help)
        operation="help"
        ;;
      *)  
        parse_error=1
        ;;
    esac
  done

  xlat_tf create_template || parse_error=1
  xlat_tf create_vms || parse_error=1

  if [[ "$parse_error" -eq 1 ]]; then
    echo "unable to parse command line, try: ./dtk help"
    exit 1
  fi

  valid_ops=(".cluster-create." ".cluster-delete." ".cluster-up." ".cluster-down." ".install-addon."
  ".verify-upstreams." ".verify-files." ".check-tools." ".help.")
  if [[ ! ${valid_ops[@]} =~ ".$operation." ]]; then
    echo "unknown operation '$operation', try: ./dtk help"
    exit 1
  fi

  if [[ -n "$addon" ]]; then
    if ! validate_addon $addon; then
      echo "unknown addon: '$addon', try: ./dtk help"
      exit 1
    fi
  fi
}

#
# Validates the config.yaml file.
#
function validate_config_file() {
  config=$(realpath $config)
  if [[ ! -f "$config" ]]; then
    echo "config file not found: $config"
    exit 1
  fi
  scripts/helpers/parse-config.py $config check || exit
}

#
# Allows the cmdline to override config.yaml.
#
function set_cmdline_overrides() {
  case $create_template in
    1)
      vm_create_template=1
      ;;
    0)
      vm_create_template=0
      ;;
  esac
}

#
# Performs configuration validation and in some cases performs configuration overrides
# (e.g., for omitted values.)
#
function validate_config_values() {
  supported_linux=(".centos9." ".rocky." ".alma8." ".alma9.")
  if [[ ! ${supported_linux[@]} =~ ".$vm_linux." ]]; then
    echo "unsupported value for linux config: $vm_linux"
    exit 1
  fi

  if [[ $virt == "virtualbox" ]]; then
    if [[ -z "$vbox_host_network_interface" ]] && [[ -z "$vbox_host_only_network" ]]; then
      echo "either --host-network-interface or --host-only-network is required"
      exit 1
    elif [[ ! -z "$vbox_host_network_interface" ]] && [[ ! -z "$vbox_host_only_network" ]]; then
      echo "--host-network-interface and --host-only-network are exclusive of each other"
      exit 1
    fi
    if [[ -z "$vbox_vboxdir" ]]; then
      vbox_vboxdir=$(vboxmanage list systemproperties | grep folder | awk -F: '{print $2}' | xargs)
    fi
    if [[ -z "$vbox_vboxdir" ]]; then
      echo "directory for virtualbox VMs is not defined"
      exit 1
    elif [[ ! -d $vbox_vboxdir ]]; then
      echo "directory for virtualbox VMs does not exist: $vbox_vboxdir"
      exit 1
    fi
  fi
}

# entry point

parse_cmdline "$@"
validate_config_file
eval $(scripts/helpers/parse-config.py $config)
validate_config_values
set_cmdline_overrides

# HERE HERE HERE TEST TEST TEST
echo "operation=$operation"
echo "create_vms=$create_vms"
echo "create_template=$create_template"
echo "config=$config"
echo "addon=$addon"
exit

export -f xec
set -a && source $DTKBASE/artifacts && set +a

case $operation in
  help)
    xec show-usage
    ;;
  create-cluster)
    xec create-cluster\
      --admin-kubeconfig=$DTKBASE/generated/kubeconfig/admin.kubeconfig\
      --ca-cert=$DTKBASE/generated/cert/ca.pem\
      --ca-key=$DTKBASE/generated/cert/ca-key.pem\
      --cluster-cidr=$k8s_cluster_cidr\
      --config=$config\
      --containerized-cplane=$k8s_containerized_cplane\
      --create-template=$vm_create_template\
      --create-vms=$create_vms\
      --host-network-interface=$vbox_host_network_interface\
      --host-only-network=$vbox_host_only_network\
      --kube-proxy-enabled=$k8s_kube_proxy\
      --linux=$vm_linux\
      --os-variant=$kvm_os_variant\
      --priv-key=$DTKBASE/generated/kickstart/id_ed25519\
      --template-vmname=$vm_template_vmname\
      --vboxdir=$vbox_vboxdir\
      --virt=$virt
    ;;
  delete-cluster)
    xec $virt/up-down-del delete $config
    ;;
  start-cluster)
     xec $virt/up-down-del up $config
    ;;
  stop-cluster)
    xec $virt/up-down-del down $config
    ;;
  install-addon)
    xec install-addons\
      --addon=$addon\
      --admin-kubeconfig=$DTKBASE/generated/kubeconfig/admin.kubeconfig\
      --config=$config\
      --priv-key=$DTKBASE/generated/kickstart/id_ed25519
    ;;
  verify-upstreams)
    xec check-objects upstreams
    ;;
  verify-files)
    xec check-objects files
    ;;
  check-tools)
    xec check-compatibility
    ;;
esac
