---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
subsets:
- addresses:
CONTROLLER
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    app.kubernetes.io/name: kube-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
    targetPort: 10257
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
subsets:
- addresses:
CONTROLLER
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler-prometheus-discovery
  labels:
    app.kubernetes.io/name: kube-scheduler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
    targetPort: 10259
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-proxy-prometheus-discovery
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-proxy
subsets:
- addresses:
WORKERS
  ports:
  - name: http-metrics
    port: 10249
---
apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-prometheus-discovery
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - interval: 30s
    port: http-metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-proxy
