apiVersion: v1
kind: Pod
metadata:
  name: hello-local-hostpath-pod
  namespace: test-openebs
spec:
  containers:
  - name: hello-container
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "$(date) $(hostname) hello from OpenEBS Local PV" >> /mnt/store/greet.txt
        sleep 5s
      done
    volumeMounts:
    - mountPath: /mnt/store
      name: local-storage
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: local-hostpath-pvc
