#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/scripts/configure-controller\
 --controller-hostname=doc\
 --vboxdir=/sdb1/virtualbox\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --etcd-download=\
 --etcd-gzip=$proj_root/binaries/etcd-v3.5.4-linux-amd64.tar.gz\
 --kube-apiserver-download=\
 --kube-apiserver-binary=$proj_root/binaries/kube-apiserver\
 --kube-controller-manager-download=\
 --kube-controller-manager-binary=$proj_root/binaries/kube-controller-manager\
 --kube-scheduler-download=\
 --kube-scheduler-binary=$proj_root/binaries/kube-scheduler\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem
