#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

$proj_root/networking/cilium/install-cilium-networking\
 --controller-ip=$ip\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig

#$proj_root/networking/cilium/install-cilium-networking\
# --controller-ip=$ip\
# --admin-kubeconfig=$proj_root/admin/admin.kubeconfig
