#!/usr/bin/env bash

# Creates a VM with hard-coded memory/cpu characteristics and bridge networking. Runs the kickstart installation
# from the passed kickstart ISO to install CentOS. (Requires the 'gen-kickstart-iso' script to have been run
# first.) Since the kickstart script shuts the VM down upon completion, in order to fully generate a template VM it
# is necessary mount the Guest Additions ISO and restart the VM for guest additions installation. See the test
# script 'test-create-template-vm' that both creates a VM and installs guest additions.

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

$proj_root/scripts/create-vm\
 --template-vmname=nettest\
 --centos-iso-path=$proj_root/media/CentOS-8.3.2011-x86_64-dvd1.iso\
 --kickstart-iso-path=$proj_root/media/kickstart.iso\
 --host-network-interface=enp0s31f6\
 --host-only-network-name=vboxnet1\
 --vboxdir=/sdb1/virtualbox
