#!/usr/bin/env bash

# this tests configuring the controller as a worker too

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
controller_ip=$($proj_root/scripts/get-vm-ip doc)
$proj_root/scripts/configure-worker\
 --controller-ip=$controller_ip\
 --controller-hostname=doc\
 --worker-hostname=ham\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig\
 --crictl-download=\
 --crictl-binary=$proj_root/binaries/crictl-v1.22.0-linux-amd64.tar.gz\
 --runc-download=\
 --runc-binary=$proj_root/binaries/runc\
 --cni-plugins-download=\
 --cni-plugins-binary=$proj_root/binaries/cni-plugins-linux-amd64-v1.1.0.tgz\
 --containerd-download=\
 --containerd-binary=$proj_root/binaries/containerd-1.6.4-linux-amd64.tar.gz\
 --kubelet-download=\
 --kubelet-binary=$proj_root/binaries/kubelet\
 --pod-cidr=10.200.1.0/24\
 --node-labels=controller,worker\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem
