#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
nodes=doc
$proj_root/networking/calico/install-calico-networking\
 --calico-manifest-download=\
 --calico-manifest=$proj_root/binaries/calico.yaml\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig\
 --pod-cidr=10.200.0.0/16\
 --nodes="${nodes[@]}"
