#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

$proj_root/worker/misc/install-misc-bins\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --worker-ip=$ip\
 --crictl-download=\
 --crictl-binary=$proj_root/binaries/crictl-v1.22.0-linux-amd64.tar.gz\
 --runc-download=\
 --runc-binary=$proj_root/binaries/runc\
 --cni-plugins-download=\
 --cni-plugins-binary=$proj_root/binaries/cni-plugins-linux-amd64-v1.0.0.tgz\

#$proj_root/worker/misc/install-misc-bins\\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --worker-ip=$ip\
# --crictl-download=https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.22.0/crictl-v1.22.0-linux-amd64.tar.gz\
# --crictl-binary=$proj_root/binaries\
# --runc-download=https://github.com/opencontainers/runc/releases/download/v1.0.1/runc.amd64\
# --runc-binary=$proj_root/binaries/runc\
# --cni-plugins-download=https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz\
# --cni-plugins-binary=$proj_root/binaries\
