#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

$proj_root/worker/containerd/install-containerd\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --worker-ip=$ip\
 --containerd-download=\
 --containerd-binary=$proj_root/binaries/containerd-1.6.0-linux-amd64.tar.gz

#$proj_root/worker/containerd/install-containerd\\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --worker-ip=$ip\
# --containerd-download=https://github.com/containerd/containerd/releases/download/v1.6.0/containerd-1.6.0-linux-amd64.tar.gz\
# --containerd-binary=$proj_root/binaries
