#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
nodes=doc
$proj_root/networking/calico/install-calico-networking\
 --calico-download=https://github.com/projectcalico/calico/releases/download/v3.23.2/release-v3.23.2.tgz\
 --calico-binary=$proj_root/binaries/calico-v3.23.2.tgz\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig\
 --pod-cidr=10.200.0.0/16\
 --nodes="${nodes[@]}"
