#!/usr/bin/env bash

#
# Tests creation of a template VM, which creates a new VM and then installs guest additions into that
# VM. The resulting VM should be suitable to clone into the controller VM and worker VMs for the Kubernetes
# cluster.
#

set -e

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ "host-only" == "$1" ]]; then
  echo "testing host-only template VM creation"
  $proj_root/scripts/create-template-vm\
   --template-vmname=bingo\
   --centos-iso-download=http://mirror.umd.edu/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso\
   --centos-iso-path=$proj_root/media/CentOS-8.3.2011-x86_64-dvd1.iso\
   --guest-additions-download=http://download.virtualbox.org/virtualbox/6.1.14/VBoxGuestAdditions_6.1.14.iso\
   --guest-additions-path=$proj_root/media/VBoxGuestAdditions_6.1.14.iso\
   --host-network-interface=\
   --host-only-network=55.1.1\
   --vboxdir=/sdb1/virtualbox
else
  echo "testing bridged template VM creation"
  $proj_root/scripts/create-template-vm\
   --template-vmname=bingo\
   --centos-iso-download=http://mirror.umd.edu/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso\
   --centos-iso-path=$proj_root/media\
   --guest-additions-download=http://download.virtualbox.org/virtualbox/6.1.14/VBoxGuestAdditions_6.1.14.iso\
   --guest-additions-path=$proj_root/media\
   --host-network-interface=enp0s31f6\
   --host-only-network=\
   --vboxdir=/sdb1/virtualbox
fi
