#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

$proj_root/control-plane/kube-controller-manager/install-kube-controller-manager\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --controller-ip=$ip\
 --controller-hostname="$1"\
 --kube-controller-manager-binary=$proj_root/binaries/kube-controller-manager\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem

#$proj_root/control-plane/kube-controller-manager/install-kube-controller-manager\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --controller-ip=$ip\
# --controller-hostname="$1"\
# --kube-controller-manager-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-controller-manager\
# --kube-controller-manager-binary=$proj_root/binaries\
# --ca-cert=$proj_root/tls/ca.pem\
# --ca-key=$proj_root/tls/ca-key.pem
