#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")
nodes="doc,ham,monk"

$proj_root/networking/kube-proxy/install-kube-proxy\
 --controller-ip=$ip\
 --kube-proxy-download=\
 --kube-proxy-binary=$proj_root/binaries/kube-proxy\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --nodes=$nodes\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem

#$proj_root/networking/kube-proxy/install-kube-proxy\
# --controller-ip=$ip\
# --kube-proxy-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-proxy\
# --kube-proxy-binary=$proj_root/binaries/kube-proxy\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --nodes=$nodes\
# --ca-cert=$proj_root/tls/ca.pem\
# --ca-key=$proj_root/tls/ca-key.pem
