#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")
$proj_root/control-plane/etcd/install-etcd\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --controller-hostname="$1"\
 --etcd-download=https://github.com/etcd-io/etcd/releases/download/v3.5.2/etcd-v3.5.2-linux-amd64.tar.gz\
 --etcd-gzip=$proj_root/binaries/etcd-v3.5.2-linux-amd64.tar.gz\
 --kubernetes-cert=$proj_root/tls/kubernetes.pem\
 --kubernetes-key=$proj_root/tls/kubernetes-key.pem\
 --ca-cert=$proj_root/tls/ca.pem
