#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "need a cluster hostname in arg 1"
  exit 1
fi

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

#$proj_root/monitoring/kube-prometheus/install-kube-prometheus\
# --controller-ip=$ip\
# --kube-prometheus-download=\
# --kube-prometheus-binary=$proj_root/binaries/kube-prometheus-0.7.0.tar.gz\
# --admin-kubeconfig=$proj_root/admin/admin.kubeconfig

$proj_root/monitoring/kube-prometheus/install-kube-prometheus\
 --controller-ip=$ip\
 --kube-prometheus-download=https://github.com/prometheus-operator/kube-prometheus/archive/v0.7.0.tar.gz\
 --kube-prometheus-binary=$proj_root/binaries/kube-prometheus-0.7.0.tar.gz\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig
