#!/usr/bin/env bash

vmname="$1"
if [[ -z "$vmname" ]]; then
  echo "need a VM name in arg 1"
  exit 1
fi

# if args not provided, then will be passed to clone-vm as empty which is suitable for bridged networking. Note:
# caller must provide both or neither - script does not validate
host_only_network="$2"
host_only_octet="$3"

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/scripts/clone-vm\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --template-vmname=bingo\
 --clone-vmname=$vmname\
 --clone-ram=2048\
 --clone-cpu=1\
 --host-only-network=$host_only_network\
 --host-only-octet=$host_only_octet\
 --vboxdir=/sdb1/virtualbox\
 --shutdown=false
