#!/usr/bin/env bash

#
# Generates tls/ca.pem and tls/ca-key.pem which are universally used throughout the project. Obviously needs
# to be static throughout the entire process of bringing up a cluster
#

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/scripts/gen-root-ca