#!/usr/bin/env bash

# bridged. Fill in host-only... for host only and NAT
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/toplevel-scripts/provision-controller\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --template-vmname=bingo\
 --host-only-network=\
 --host-only-octet=\
 --vboxdir=/sdb1/virtualbox\
 --controller-hostname=doc\
 --controller-ram=4096\
 --controller-cpu=2\
 --controller-disk=20000\
 --etcd-download=\
 --etcd-gzip=$proj_root/binaries/etcd-v3.5.2-linux-amd64.tar.gz\
 --kube-apiserver-download=\
 --kube-apiserver-binary=$proj_root/binaries/kube-apiserver\
 --kube-controller-manager-download=\
 --kube-controller-manager-binary=$proj_root/binaries/kube-controller-manager\
 --kube-scheduler-download=\
 --kube-scheduler-binary=$proj_root/binaries/kube-scheduler\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem\
