#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ip=$($proj_root/scripts/get-vm-ip "$1")

$proj_root/networking/kube-router/install-kube-router\
 --controller-ip=$ip\
 --kube-router-yaml-download=\
 --kube-router-yaml=$proj_root/binaries/generic-kuberouter-all-features.yaml\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig

#$proj_root/networking/kube-router/install-kube-router\
# --controller-ip=$ip\
# --kube-router-yaml-download=https://raw.githubusercontent.com/cloudnativelabs/kube-router/v1.3.1/daemonset/generic-kuberouter-all-features.yaml\
# --kube-router-yaml=$proj_root/binaries\
# --admin-kubeconfig=$proj_root/admin/admin.kubeconfig
