#!/usr/bin/env bash

set -e

#
# Tests getting the CentOS ISO
#

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir=$(mktemp -d)

if ! $proj_root/scripts/download-obj\
 --url=http://mirror.umd.edu/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso\
 --dest=$proj_root/media/CentOS-8.3.2011-x86_64-dvd1.iso; then
   echo "download failed - ISO does not exist at specified URL?"
fi

echo "success"
