#!/usr/bin/env bash

# Key pair eventually gets wired into the template VM. So the private key can be used to SSH
# into any VM cloned from the template.

set -e

if [[ ! -f $DTKBASE/generated/kickstart/id_ed25519 ]] || [[ ! -f $DTKBASE/generated/kickstart/id_ed25519.pub ]]; then
  echo "generating key pair"
  ssh-keygen -t ed25519 -N '' -f $DTKBASE/generated/kickstart/id_ed25519 <<<y
else
  echo "key pair already exists"
fi
