#!/usr/bin/env bash

set -e

long_opts=calico-tigera-binary:,calico-custom-resources-manifest:,priv-key:,admin-kubeconfig:,cluster-cidr:,nodes:
script_name=$(basename "$0")
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

calico_tigera_binary=
calico_custom_resources_manifest=
priv_key=
admin_kubeconfig=
cluster_cidr=
nodes=()

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --calico-tigera-binary)
        calico_tigera_binary=$(opt_val "$2")
        shift 2
        ;;
      --calico-custom-resources-manifest)
        calico_custom_resources_manifest=$(opt_val "$2")
        shift 2
        ;;
      --priv-key)
        priv_key=$(opt_val "$2")
        shift 2
        ;;
      --admin-kubeconfig)
        admin_kubeconfig=$(opt_val "$2")
        shift 2
        ;;
      --cluster-cidr)
        cluster_cidr=$(opt_val "$2")
        shift 2
        ;;
      --nodes)
        nodes=$(opt_val "$2")
        IFS=',' read -ra nodes <<< "$nodes"
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

# per https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
# last eyeballed on 14-Jul-2022
for node in "${nodes[@]}"; do
  worker_ip=$(xec get-vm-ip $node)
  ssh -i $priv_key root@$worker_ip << EOF
    echo -e "[keyfile]\nunmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:wireguard.cali"\
      >| /etc/NetworkManager/conf.d/calico.conf
    systemctl daemon-reload && systemctl restart NetworkManager
EOF
done

# Goal is to patch the upstream manifest and leave the upstream un-touched. As of v3.24.1
# the ipPools value in the upstream was "cidr: 192.168.0.0/16". If that changes, then error,
# otherwise calico will be mis-configured because the sed expression won't be correct for
# the manifest
if ! grep -q 'cidr: 192.168.0.0/16' $calico_custom_resources_manifest; then
  echo "Calico manifest $calico_tigera_binary not as expected"
  exit 1
fi

echo "deploying calico tigera and custom resources"
kubectl --kubeconfig $admin_kubeconfig create -f $calico_tigera_binary

kubectl --kubeconfig $admin_kubeconfig  wait --for condition=established\
  crd/installations.operator.tigera.io crd/apiservers.operator.tigera.io --timeout=1m

# these are cluster-scoped, hence no namespace
echo "deploying calico Installation and APIServer resources"
sed "s|cidr: 192.168.0.0/16|cidr: $cluster_cidr|" $calico_custom_resources_manifest\
  | kubectl --kubeconfig $admin_kubeconfig create -f -

echo "waiting (indefinitely) for calico daemonset"
while true; do
  if kubectl --kubeconfig $admin_kubeconfig -n calico-system rollout status ds calico-node; then
    break
  fi
  sleep 10s
done

echo "calico installation complete"
