{
   "apiVersion" : "apiserver.k8s.io/v1beta1",
   "EgressSelections" : [
      {
         "Connection" : {
            "ProxyProtocol" : "Direct",
            "Transport" : null
         },
         "Name" : "cluster"
      }
   ],
   "kind" : "EgressSelectorConfiguration"
}
