#!/usr/bin/env bash

set -e

long_opts=config:,admin-kubeconfig:,priv-key:,addon:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

config=
admin_kubeconfig=
priv_key=
addon=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

# write info to config yaml for addons
yq -i '.cluster.admin-kubeconfig = "'$admin_kubeconfig'"' $config
yq -i '.cluster.priv-key = "'$priv_key'"' $config

if [[ -n "$addon" ]]; then
  if [[ -d $script_dir/$addon ]]; then
    echo "installing $addon in $script_dir/$addon"
    $script_dir/$addon/install $config
  else
    echo "addon directory not found: $script_dir/$addon"
  fi
else
  for ((i = 0; i < $(yq '.addons | length' $config); ++i)); do
    addon="$(yq .addons[$i].name $config)"
    enabled="$(yq .addons[$i].enabled $config)"
    if [[ -d $script_dir/$addon ]]; then
      if [[ $enabled == "true" ]]; then
        echo "installing $addon in $script_dir/$addon"
        $script_dir/$addon/install $config
      fi
    else
      echo "addon directory not found (skipping): $script_dir/$addon"
    fi
  done
fi
