#!/usr/bin/env bash

config=$1

KUBE_PROM_VER=55.5.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

url=https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-$KUBE_PROM_VER/kube-prometheus-stack-$KUBE_PROM_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)

helm_arg="set kubeEtcd.endpoints={}"
containerized_cplane=$(yq .k8s.containerized-cplane $config)

# if etcd is running as a systemd service rather than a pod, have to tell kube-prometheus that
if [[ "$containerized_cplane" != *etcd* && "$containerized_cplane" != all ]]; then
  endpoint=$(kubectl --kubeconfig $admin_kubeconfig get node  -l node-role.kubernetes.io/controller\
    -o json | jq -r '.items[].status.addresses[] | select(.type=="InternalIP").address')
  helm_arg="set kubeEtcd.endpoints={$endpoint}"
fi

helm upgrade --install kube-prometheus\
  --namespace kube-prometheus\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --$helm_arg\
  --values $script_dir/values.yaml\
  $tgz 

echo "TODO for all components that are not pods, customize the values"
