#!/usr/bin/env bash

# Generates root CA cert and key. These will be used to sign every other cert generated for
# the cluster.

openssl genrsa -out "$DTKBASE/generated/cert/ca-key.pem" 2048
openssl req -x509 -new -nodes -key "$DTKBASE/generated/cert/ca-key.pem" -sha256\
 -subj "/CN=internalca" -days 10000 -out "$DTKBASE/generated/cert/ca.pem"
