#!/usr/bin/env bash

# Generates root CA cert and key if they don't already exist. These will be used to sign
# every other cert generated for the cluster. There's no need to continually regenerate these
# so if they already exist just keep re-using them.
#
# Outputs:
#   - $DTKBASE/$GENERATED/cert/ca-key.pem
#   - $DTKBASE/$GENERATED/cert/ca.pem

mapfile -t certfiles < <(ls -1 $DTKBASE/$GENERATED/cert/ca{,-key}.pem)

if [[ "${#certfiles[@]}" -eq 2 ]]; then
  echo "CA cert and key already exist - skipping"
  exit
fi

openssl genrsa\
  -out "$DTKBASE/$GENERATED/cert/ca-key.pem"\
  2048

openssl req\
  -x509\
  -new\
  -nodes\
  -key "$DTKBASE/$GENERATED/cert/ca-key.pem"\
  -sha256\
  -subj "/CN=internalca"\
  -days 10000\
  -out "$DTKBASE/$GENERATED/cert/ca.pem"\
  -addext "basicConstraints=critical,CA:TRUE"\
  -addext "keyUsage=critical,digitalSignature,keyCertSign,cRLSign"
