apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  containers:
  - name: main
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - tail -f /dev/null
    volumeMounts:
    - mountPath: /tmp/foo
      name: test-vol
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: test-pvc-2

