#!/usr/bin/env bash
#
# Helm-installs the External DNS. Note - the webhook server must be running when you
# run this install or external dns will error...
#

config=$1

CHART_VER=1.20.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
url=https://github.com/kubernetes-sigs/external-dns/releases/download/external-dns-helm-chart-$CHART_VER/external-dns-$CHART_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

controller_hostname=$(yq .vms[0].name $config)
virt=$(yq .virt $config)
controller_ip=$(xec $virt/get-vm-ip $controller_hostname)

dns_host_ip=$(yq .dns.host-ip $config)
dns_webhook_port=$(yq .dns.webhook-port $config)
dns_domain=$(yq .dns.domain $config)

# configure the webhook server
curl -X POST "http://$dns_host_ip:$dns_webhook_port/domains" -d "$dns_domain"
curl -X POST "http://$dns_host_ip:$dns_webhook_port/clusterip" -d "$controller_ip"

cat <<EOF >| $script_dir/extra-values.yaml
extraArgs:
  - --webhook-provider-url=http://$dns_host_ip:$dns_webhook_port
EOF

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)
helm upgrade --install external-dns $tgz\
  --namespace external-dns\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  --values $script_dir/extra-values.yaml\
  --wait
