kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: /var/lib/kubernetes/ca.pem
authorization:
  mode: Webhook
clusterDomain: cluster.local
clusterDNS:
  - 10.32.0.10
podCIDR: 10.200.1.0/24
# not needed for CentOS:
#https://github.com/bserdar/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md
# says:
# TUE NITE PUT THIS BACK!!
resolvConf: "/etc/resolv.conf"
#resolvConf: /run/systemd/resolve/resolv.conf <<<<<<<<<<<<<<<<<<<<<<<
runtimeRequestTimeout: 15m
tlsCertFile: /var/lib/kubelet/worker.pem
tlsPrivateKeyFile: /var/lib/kubelet/worker-key.pem
