#!/usr/bin/env bash
#
# Helm-installs cilium.
#

config=$1

CILIUM_VER=1.18.5

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
url=https://helm.cilium.io/cilium-$CILIUM_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

controller_hostname=$(yq .vms[0].name $config)
virt=$(yq .virt $config)
controller_ip=$(xec $virt/get-vm-ip $controller_hostname)
sed "s|K8SSERVICEHOST|$controller_ip|g" $script_dir/values-template.yaml >| $script_dir/values.yaml

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)
helm upgrade --install cilium $tgz\
  --namespace cilium\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  --wait

echo "waiting (indefinitely) for cilium daemonset"
while true; do
  if kubectl --kubeconfig $admin_kubeconfig -n cilium rollout status ds cilium; then
    break
  fi
  sleep 10s
done
