k8sServiceHost: K8SSERVICEHOST
k8sServicePort: 6443
kubeProxyReplacement: "true"
operator:
  replicas: 1
ipam:
  # mode kubernetes per - https://docs.cilium.io/en/stable/network/concepts/ipam/kubernetes/
  mode: kubernetes
#hubble:
#  relay:
#    enabled: true
#  ui:
#    enabled: true
#  metrics:
#    enabled:
#      - dns
#      - drop
#      - tcp
#      - flow
#      - port-distribution
#      - icmp
#      - dns:labelsContext=source_namespace,destination_namespace
#      - drop:labelsContext=source_namespace,destination_namespace
#      - httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction