#!/usr/bin/env bash
#
# Creates a template VM the way the 'dtk' script does it.
#
# Args:
#
# --host-only-network <octets>
# --host-network-interface <interface name>
# --os-iso <path to OS iso>
# --ga-iso <path to guest additions ISO>
# --vm-name <name>
# --vbox-dir <dir>
# --ks <name>
#
# Examples:
#
# hack/create-vm\
#   --host-only-network 192.168.56\
#   --os-iso $PWD/binaries/CentOS-Stream-9-latest-x86_64-dvd1.iso\
#   --ga-iso $PWD/binaries/VBoxGuestAdditions_7.0.18.iso\
#   --vm-name centos9-stream\
#   --ks vbox.text.ks.cfg
# 
# hack/create-vm\
#   --host-network-interface enp0s31f6\
#   --os-iso $PWD/binaries/AlmaLinux-9.3-x86_64-dvd.iso\
#   --ga-iso $PWD/binaries/VBoxGuestAdditions_7.0.18.iso\
#   --vm-name alma93
# 

export DTKBASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
function xec() {
  if echo $1 | grep -q /; then
    f=$(find . -type d -name $(dirname $1) | xargs -I% find % -type f -name $(basename $1))
  else
    f=$(find $DTKBASE/scripts -name $1)
  fi
  [[ -n $f ]] && $f "${@:2}"
}
export -f xec

hostonly=
hni=
os_iso=
ga_iso=
vmname=
ks=
vboxdir=$(vboxmanage list systemproperties | grep folder | awk -F: '{print $2}' | xargs)

for ((i = 1; i <= $#; i++ )); do
  if [[ ${!i} == "--os-iso" ]]; then
    ((i++))
    os_iso=${!i}
  elif [[ ${!i} == "--ga-iso" ]]; then
    ((i++))
    ga_iso=${!i}
  elif [[ ${!i} == "--host-only-network" ]]; then
    ((i++))
    hostonly=${!i}
  elif [[ ${!i} == "--host-network-interface" ]]; then
    ((i++))
    hni=${!i}
  elif [[ ${!i} == "--vm-name" ]]; then
    ((i++))
    vmname=${!i}
  elif [[ ${!i} == "--vbox-dir" ]]; then
    ((i++))
    vboxdir=${!i}
  elif [[ ${!i} == "--ks" ]]; then
    ((i++))
    ks=${!i}
  else
    echo unknown param: ${!i}
    exit 1
  fi
done

xec virtualbox/create-template-vm\
  --template-vmname=$vmname\
  --linux-iso-path=$os_iso\
  --guest-additions-path=$ga_iso\
  --host-network-interface=$hni\
  --host-only-network=$hostonly\
  --vboxdir=$vboxdir\
  --kickstart=$ks
