#!/usr/bin/env bash

#
# Downloads an object to the filesystem if it does not already exist there.
#
# Usage:
#
# download-obj --url=https://foobar.com/downloads/frobozz.tar.gz --dest="/tmp/downloads/frobozz.tar.gz"
#
# The --dest arg specifies a fully qualified path and file name. All directories must exist. The script will
# not create them. Optional --executable arg does a chmod +x on the downloaded file

set -e

# api
url=
dest=

# internal
executable=0

short_opts=u:d:x
long_opts=url:,dest:,executable
script_name=$(basename "$0")

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

parsed=$(getopt --options $short_opts --longoptions $long_opts -n $script_name -- "$@")

if [[ "$?" -ne 0 ]]; then
  exit 1
fi

eval set -- "$parsed"

while true; do
  case "$1" in
    -u|--url)
      url=$(opt_val "$2")
      shift 2
      ;;
    -d|--dest)
      dest=$(opt_val "$2")
      shift 2
      ;;
    -x|--executable)
      executable=1
      shift 1
      ;;
    --)
      shift
      break
      ;;
  esac
done

# $# below is the left over args - and there shouldn't be any
if [[ -z "$url" ]] || [[ -z "$dest" ]] || [[ "$#" -ne 0 ]]; then
  echo "invalid args"
  exit 1
fi

if [[ ! -f "$dest" ]]; then
  echo "downloading $url"
  curl -sL "$url" -o "$dest"
  if [[ $executable -eq 1 ]]; then
    chmod +x "$dest"
  fi
else
  echo "$dest already exists, skipping download"
fi
