#!/usr/bin/env bash
#
# Downloads an object to the filesystem if it does not already exist there.
#
# Usage:
#
# download-obj --url=https://foobar.com/downloads/frobozz.tar.gz --dest="/tmp/downloads/frobozz.tar.gz"
#
# The --dest arg specifies a fully qualified path and file name. The script will create all intermediate
# directories if they don't exist. Optional --executable arg does a chmod +x on the downloaded file
#

set -e
long_opts=url:,dest:,executable
script_name=$(basename "$0")

url=
dest=
executable=0

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --url)
        url=$(opt_val "$2")
        shift 2
        ;;
      --dest)
        dest=$(opt_val "$2")
        shift 2
        ;;
      --executable)
        executable=1
        shift 1
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

if [[ -z "$url" ]] || [[ -z "$dest" ]]; then
  echo "invalid args"
  exit 1
fi

mkdir -p $(dirname "$dest")

if [[ ! -f "$dest" ]]; then
  echo "downloading $url"
  curl -sL "$url" -o "$dest"
  if [[ $executable -eq 1 ]]; then
    chmod +x "$dest"
  fi
else
  echo "$dest already exists, skipping download"
fi
