#!/usr/bin/env bash
#
# Downloads an object to the filesystem if it does not already exist there.
#
# Usage:
#
# download-obj --url=https://foobar.com/downloads/frobozz.tar.gz --dest="/tmp/downloads/frobozz.tar.gz"
#
# The --dest arg specifies a fully qualified path and file name. The script will create all intermediate
# directories if they don't exist. Optional --executable arg does a chmod +x on the downloaded file
#

set -e
long_opts=url:,dest:,executable

url=
dest=
executable=0

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

if [[ -z "$url" ]] || [[ -z "$dest" ]]; then
  echo "invalid args"
  exit 1
fi

mkdir -p $(dirname "$dest")

if [[ ! -f "$dest" ]]; then
  echo "downloading $url"
  curl -sL "$url" -o "$dest"
  if [[ $executable -eq 1 ]]; then
    chmod +x "$dest"
  fi
else
  echo "$dest already exists, skipping download"
fi
