#!/usr/bin/env bash
#
# Prints elapsed time in H:MM:SS:NNN. Both input times have to be 13-digit time
# values as shown in the usage example.
#
# Usage example:
#
# start=$(date +%s%N | cut -b1-13); read; stop=$(date +%s%N | cut -b1-13); ./elapsed $start $stop; echo
#

start="$1"
stop="$2"
message="$3"

if [[ "${#start}" -ne 13 ]] || [[ "${#stop}" -ne 13 ]]; then
  echo "error: both values must be 13-position numbers"
  exit 1
fi

# in case the values are passed with leading zeros, make bash interpret them as base ten instead of octal
elapsed="$(($((10#$stop))-$((10#$start))))"

if [[ $elapsed -lt 0 ]]; then
  echo "error: the first parameter value must be earlier than second parameter value"
  exit 1
fi

# hours
millis_hr=$((1000 * 60 * 60))
elapsed_hr=$((elapsed / millis_hr))

# minutes
elapsed=$((elapsed - (elapsed_hr * millis_hr)))
millis_min=$((1000 * 60))
elapsed_min=$((elapsed / millis_min))

# seconds
elapsed=$((elapsed - (elapsed_min * millis_min)))
millis_sec=$((1000))
elapsed_sec=$((elapsed / millis_sec))

# millis
elapsed_milli=$((elapsed - (elapsed_sec * millis_sec)))

printf "%d:%02d:%02d:%03d" $elapsed_hr $elapsed_min $elapsed_sec $elapsed_milli
