#!/usr/bin/env bash
#
# Parse the yaml configuration for k8s, vbox, and vm keys. Faster
# then 'yq', so - kept it around.
#

CFGFILE="$1" python3 <<END
import yaml, sys, os

valid_configs = [
    "k8s.containerized-cplane",
    "k8s.cluster-cidr",
    "k8s.cluster-dns",
    "k8s.kube-proxy",
    "vbox.host-network-interface",
    "vbox.host-only-network",
    "vbox.vboxdir",
    "vm.linux",
    "vm.create-template",
    "vm.template-vmname"
]

config_file = os.environ['CFGFILE']

with open(config_file, "r") as file:
    cfg = yaml.safe_load(file)

vars = ""
newline = ""

for key in list(cfg.keys()):
   if not key in ["k8s", "vbox", "vm"]:
        continue
   for subkey in list(cfg[key].keys()):
        config = "%s.%s" % (key, subkey)
        if not config in valid_configs:
            print("error: unsupported configuration: " + config)
            exit(1)
        val = "" if cfg[key][subkey] is None else cfg[key][subkey]
        if str(val) == "True":
            val = "1"
        elif str(val) == "False":
            val = "0"
        var = (key + "-" + subkey).replace("-", "_")
        vars = vars + "%s%s=%s" % (newline, var, val)
        newline = "\n"
print(vars)
END
