#!/usr/bin/env bash

set -e

priv_key=$1
IFS=',' read -ra nodes <<< $2

echo "To access the cluster node(s) via ssh:"
echo
for node in "${nodes[@]}"
do
  ip=$(xec get-vm-ip $node)
  echo "$node: ssh -i $priv_key root@$ip"
done
