#!/usr/bin/env bash

set -e

priv_key=$1
config=$2

echo "To access the cluster node(s) via ssh:"
echo
for ((i = 0; i < $(yq '.vms | length' $config); ++i)); do
  node=$(yq .vms[$i].name $config)
  ip=$(xec get-vm-ip $node)
  echo "$node: ssh -i $priv_key root@$ip"
done
