#!/usr/bin/env bash
#
# Shows the dtk usage instructions.
#

while IFS= read -r line; do
  echo "${line:2}"
done <<< '
  dtk (desktop kubernetes)
  ------------------------
  Creates a Kubernetes cluster on the desktop using kickstart, KVM or VirtualBox, and choice of
  CentOS, Rocky, or Alma Linux as the guest OS. The cluster consists of a configurable number of
  guest VMs with each guest running one node. The nodes are configured with networking support
  for host-to-guest, guest-to-guest, and guest-to-internet.

  The script first creates a re-usable template VM by using kickstart to install the guest OS
  hands-free. Thereafter, clones the template VM for each cluster node and each new cluster.
  (The template VM can be regenerated and multiple templates can be maintained.)

  Cluster and VM configuration are specified in a config.yaml file. By default, the CLI looks for
  config.yaml in the same directory as the CLI was executed from, but this can be overridden with
  a command line option.

  Usage:
  
    dtk command [sub-command] [flags]

  Supported commands, sub-commands, and operands:

    command        sub-cmd / operand  Description
    -------------  -----------------  -----------
    cluster        create             Creates a cluster per the config.yaml file.
                   up                 Starts all the VMs in config.yaml.
                   down               Stops all the VMs in config.yaml.
                   delete             Deletes a cluster by deleting all the VMs in config.yaml.
    verify         upstreams          Does a curl HEAD request on all core k8s components, ISOs.
                   files              Reports on which core k8s components have already been
                                      downloaded to the file system.
    install-addon  The addon name     Install an add-on from the scripts/addons directory.
    check-tools    n/a                Reports on the presence or absence, and version, of the tools
                                      used by the CLI to provision a cluster.
    version        n/a                Displays the version.
    help           n/a                Displays this help.

  Options:

    --config           The path to a configuration yaml file that specifies the cluster
                       options. If not provided, uses the config.yaml file in the same directory
                       as the CLI.
    --create-template  Overrides the setting specified in the configuration yaml. Allowed values
                       are "true" and "false".
    --create-vms       Create VMs. Allowed values are "true" and "false". Default is true. If
                       false, then the VMs in the config.yaml file must be up and running, and the
                       installer will simply install Kubernetes on them.
    --help             Same as the help command.

  Examples:

    ./dtk cluster create --config mycluster.yaml

    Creates a cluster as defined in "mycluster.yaml" file.

    ./dtk cluster create --create-template=false

    Like above except re-uses the existing template from a prior cluster creation, and
    uses the config.yaml in the CLI dir. (The config.yaml specifies the name of the
    template VM.)

    ./dtk cluster up

    Starts the VMs listed in the config.yaml in the CLI dir.

    ./dtk install-addon external-dns

    Installs the external-dns add-on from scripts/addons.'
