installation:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: CLUSTERCIDR
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

# disable Calico CSI
kubeletVolumePluginPath: None
