installation:
  # per https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io%2fv1.CalicoNetworkSpec
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: CLUSTERCIDR
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

# disable Calico CSI
kubeletVolumePluginPath: None
