#!/usr/bin/env bash
#
# Helm-installs the Kubernetes Dashboard.
#

config=$1

CHART_VER=7.14.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
url=https://github.com/kubernetes/dashboard/releases/download/kubernetes-dashboard-$CHART_VER/kubernetes-dashboard-$CHART_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)
helm upgrade --install kubernetes-dashboard $tgz\
  --namespace kubernetes-dashboard\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  --wait
