#!/usr/bin/env bash
#
# Helm-installs the Kubernetes Dashboard.
#

config=$1

KUBE_DASHBOARD_VER=7.12.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
url=https://github.com/kubernetes/dashboard/releases/download/kubernetes-dashboard-$KUBE_DASHBOARD_VER/kubernetes-dashboard-$KUBE_DASHBOARD_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)
helm upgrade --install kubernetes-dashboard\
  --namespace kubernetes-dashboard\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  $tgz
