#!/usr/bin/env bash
#
# Install the server as a systemd service using this script. Run this script from
# the root of the cloned repository.
#

set -e

scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $(id -u) -ne 0 ]]; then
  echo "must run as root"
  exit 1
fi

cp $scriptdir/hostsfile-server.py /usr/bin/
cp $scriptdir/hostsfile-server.service /etc/systemd/system/
systemctl enable --now hostsfile-server
