#!/usr/bin/env bash

set -e

long_opts=controller-ip:,admin-kubeconfig:
script_name=$(basename "$0")
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

controller_ip=
admin_kubeconfig=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --controller-ip)
        controller_ip=$(opt_val "$2")
        shift 2
        ;;
      --admin-kubeconfig)
        admin_kubeconfig=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

# debug
#echo "controller_ip=$controller_ip"
#echo "admin_kubeconfig=$admin_kubeconfig"

sed $proj_root/networking/cilium/cilium-1.9.4-quick-install.yaml -e "s|CONTROLLER_IP|$controller_ip|g"\
 | kubectl --kubeconfig $admin_kubeconfig apply -f -
sleep 3s

echo "waiting for pod networking"

kubectl --kubeconfig $admin_kubeconfig -nkube-system wait pod -lio.cilium/app=operator --for condition=ready --timeout=1m
kubectl --kubeconfig $admin_kubeconfig -nkube-system wait pod -lk8s-app=cilium --for condition=ready --timeout=1m

echo "installing Cilium Hubble"

kubectl --kubeconfig $admin_kubeconfig apply -f $proj_root/networking/cilium/cilium-1.9.4-quick-hubble-install.yaml

kubectl --kubeconfig $admin_kubeconfig -nkube-system wait pod -lk8s-app=hubble-ui --for condition=ready --timeout=1m
kubectl --kubeconfig $admin_kubeconfig -nkube-system wait pod -lk8s-app=hubble-relay --for condition=ready --timeout=1m
