#!/usr/bin/env bash

config=$1

METRICS_SERVER_VER=3.12.2

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)

url=https://github.com/kubernetes-sigs/metrics-server/releases/download/metrics-server-helm-chart-$METRICS_SERVER_VER/metrics-server-$METRICS_SERVER_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

helm upgrade --install metrics-server\
  --namespace metrics-server\
  --create-namespace\
  --wait\
  --kubeconfig $admin_kubeconfig\
  $tgz
