#!/usr/bin/env bash
#
# Note - when you install Cilium, it moves 10-containerd-net.conflist to
# 10-containerd-net.conflist.cilium_bak on each host.
#

set -e

long_opts=controller-ip:,admin-kubeconfig:
script_name=$(basename "$0")
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

controller_ip=
admin_kubeconfig=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --controller-ip)
        controller_ip=$(opt_val "$2")
        shift 2
        ;;
      --admin-kubeconfig)
        admin_kubeconfig=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

sed "s|K8SSERVICEHOST|$controller_ip|g" $script_dir/cilium.values.yaml\
  >| $DTKBASE/binaries/cilium.values.yaml

echo "installing Cilium & Hubble"

helm install cilium $CILIUM_BINARY\
  --values $DTKBASE/binaries/cilium.values.yaml\
  --namespace cilium\
  --create-namespace\
  --kubeconfig $admin_kubeconfig

echo "waiting (indefinitely) for cilium daemonset"
while true; do
  if kubectl --kubeconfig $admin_kubeconfig -n cilium rollout status ds cilium; then
    break
  fi
  sleep 10s
done
