#!/usr/bin/env bash
#
# Creates a template VM.
#

set -e

long_opts=template-vmname:,linux:,host-only-network:,kickstart:,os-variant:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

template_vmname=
linux=
host_only_network=
kickstart=
os_variant=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

linux_iso_path=
if [[ $linux == "alma8" ]]; then
  linux_iso_path=$ALMA8_ISO_FILE
elif [[ $linux == "alma9" ]]; then
  linux_iso_path=$ALMA9_ISO_FILE
elif [[ $linux == "alma10" ]]; then
  linux_iso_path=$ALMA10_ISO_FILE
elif [[ $linux == "rocky" ]]; then
  linux_iso_path=$ROCKY_ISO_FILE
elif [[ $linux == "centos9" ]]; then
  linux_iso_path=$CENTOS9_ISO_FILE
else
  echo "unknown/unspecified linux distro"
  exit 1
fi

echo "checking/generating SSH keys"
xec gen-ssh-keyfiles

echo "interpolating SSH key into kickstart file"
ksout=$DTKBASE/generated/kickstart
sshkey=$(<$DTKBASE/generated/kickstart/id_ed25519.pub)
sed "s/REPLACE-WITH-SSHKEY/$sshkey/" $DTKBASE/kickstarts/$kickstart >| $ksout/ks.cfg

# memory is MiB
echo "creating VM"
virt-install\
  --noautoconsole\
  --name $template_vmname\
  --memory 2000\
  --vcpus 2\
  --disk size=30\
  --location $linux_iso_path\
  --boot hd,cdrom\
  --graphics none\
  --os-variant $os_variant\
  --initrd-inject $ksout/ks.cfg\
  --extra-args="inst.ks=file:/ks.cfg console=tty0 console=ttyS0,115200n8"

echo "waiting (indefinitely) for the machine to power off"
while true; do
  virsh list --all | grep $template_vmname | grep -iv running && break || sleep 10s
done

echo "template VM fully provisioned"
