#!/usr/bin/env bash

set -e

long_opts=template-vmname:,linux-iso-path:,host-only-network:,kickstart:,os-variant:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

template_vmname=
linux_iso_path=
host_only_network=
kickstart=
os_variant=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

echo "checking/generating SSH keys"
xec gen-ssh-keyfiles

echo "interpolating SSH key into kickstart file"
ksout=$DTKBASE/generated/kickstart
sshkey=$(<$DTKBASE/generated/kickstart/id_ed25519.pub)
sed "s/REPLACE-WITH-SSHKEY/$sshkey/" $DTKBASE/kickstarts/$kickstart >| $ksout/ks.cfg

# memory is MiB
echo "creating VM"
virt-install\
  --noautoconsole\
  --name $template_vmname\
  --memory 2000\
  --vcpus 2\
  --disk size=30\
  --cdrom $linux_iso_path\
  --location $linux_iso_path\
  --boot hd,cdrom\
  --os-variant $os_variant\
  --initrd-inject $ksout/ks.cfg\
  --extra-args="ks=file:/ks.cfg console=tty0 console=ttyS0,115200n8"

echo "waiting (indefinitely) for the machine to power off"
while true; do
  virsh list --all | grep $template_vmname | grep -iv running && break || sleep 10s
done

echo "template VM fully provisioned"
