#!/usr/bin/env bash
#
# Gets the IP address of a VM.
#

vm="$1"

while true; do
  if virsh domifaddr $vm | grep -qE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
    break
  fi
  sleep 1s
done

ip=$(virsh domifaddr $vm | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | awk '{print $4}')
echo "${ip%/*}"
