#!/usr/bin/env bash
#
# Provisions VMs for the cluster. May create a template VM first if
# --create-template=true. Otherwise clones the VMs from --template-vmname
# arg.

set -e

long_opts=create-template:,linux:,vboxdir:,template-vmname:,config:,os-variant:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

create_template=0
linux=
vboxdir=
template_vmname=
config=
os_variant=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

linux_iso_path=
if [[ $linux == "alma8" ]]; then
  linux_iso_path=$ALMA8_ISO_FILE
elif [[ $linux == "alma9" ]]; then
  linux_iso_path=$ALMA9_ISO_FILE
elif [[ $linux == "rocky" ]]; then
  linux_iso_path=$ROCKY_ISO_FILE
elif [[ $linux == "centos9" ]]; then
  linux_iso_path=$CENTOS9_ISO_FILE
else
  echo "unknown/unspecified linux distro"
  exit 1
fi

# create-template-vm gens SSH keypair $DTKBASE/generated/kickstart/id_ed25519
# if it does not already exist - which is used below when cloning the VM

if [[ $create_template -eq 1 ]] ; then
  kickstart=$(yq .kvm.kickstart $config)
  echo "creating a template VM"
  $script_dir/create-template-vm\
   --template-vmname=$template_vmname\
   --linux-iso-path=$linux_iso_path\
   --kickstart=$kickstart\
   --os-variant=$os_variant
fi

vmcnt=$(yq '.vms | length' $config)
vm_names=()

for ((i = 0; i < $vmcnt; ++i)); do
  vm_name=$(yq .vms[$i].name $config)
  vm_cpu=$(yq .vms[$i].cpu $config)
  vm_mem=$(yq .vms[$i].mem $config)
  vm_ip=$(yq .vms[$i].ip $config)
  vm_disk=$(yq '.vms['$i'].disk // ""' $config)

  if [[ -n $vm_disk ]] && [[ $vm_disk -le 30 ]]; then
    echo "shrinking the disk is not supported - ignoring"
    vm_disk=
  fi

  $script_dir/clone-vm\
   --priv-key=$DTKBASE/generated/kickstart/id_ed25519\
   --template-vmname=$template_vmname\
   --clone-vmname=$vm_name\
   --clone-ram=$vm_mem\
   --clone-cpus=$vm_cpu\
   --clone-disk=$vm_disk

  vm_names+=($vm_name)
done

# do this now to avoid needing DNS before CoreDNS is installed
echo "configuring /etc/hosts in VMs"
xec kvm/configure-etc-hosts $DTKBASE/generated/kickstart/id_ed25519 "${vm_names[@]}"
