#!/usr/bin/env bash
#
# Starts / stops / deletes a cluster. Usage:
#
# up-down-del <up|down|del> <config>
#
# E.g.:
#
# up-down-del up ~/my-config.yaml
#

set -e

op="$1"
config="$2"

yq -r '.vms[].name' $config | while read vmname; do
  case $op in
    up)
      virsh start $vmname
      ;;
    down)
      virsh shutdown $vmname
      ;;
    del)
      virsh shutdown $vmname || :
      virsh destroy $vmname || :
      while true; do
        if virsh undefine $vmname --remove-all-storage; then
          break
        fi
      done
      ;;
  esac
done