#!/usr/bin/env bash

set -e

if [[ $1 == "up" ]]; then
  IFS=',' read -ra vms <<< "$2"
  for vm in "${vms[@]}"; do
    virsh start $vm
  done
  sleep 5s
elif [[ $1 == "down" ]]; then
  IFS=',' read -ra vms <<< "$2"
  for vm in "${vms[@]}"; do
    echo "shutting down $vm"
    virsh shutdown $vm
  done
elif [[ $1 == "delete" ]]; then
  IFS=',' read -ra vms <<< "$2"
  for vm in "${vms[@]}"; do
    echo "removing $vm"
    virsh undefine $vm --remove-all-storage
  done
fi
