#!/usr/bin/env bash

set -e

IFS=',' read -ra vms <<< "$2"
for vm in "${vms[@]}"; do
  if [[ $1 == "up" ]]; then
    virsh start $vm
  elif [[ $1 == "down" ]]; then
    virsh shutdown $vm
  elif [[ $1 == "delete" ]]; then
    virsh shutdown $vm || :
    virsh destroy $vm || :
    while true; do
      if virsh undefine $vm --remove-all-storage; then
        break
      fi
    done
  fi
done
