#!/usr/bin/env bash
#
# Copies crictl, runc, and cni plugins to the VM with IP
# --worker-ip.
#

set -e

long_opts=priv-key:,worker-ip:,crictl-binary:,runc-binary:,cni-plugins-binary:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

priv_key=
worker_ip=
crictl_binary=
runc_binary=
cni_plugins_binary=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

echo "Copying misc kubernetes binaries"

echo "Copying crictl binary and config to worker"
ssh -i $priv_key root@$worker_ip "tar -zxf - --no-same-owner -C /usr/local/bin/ crictl" < $crictl_binary
scp -i $priv_key $script_dir/crictl.yaml root@$worker_ip:/etc/

echo "Copying runc binary to worker"
scp -i $priv_key $runc_binary root@$worker_ip:/usr/local/bin/runc

echo "Copying cni plugins binary to worker"
ssh -i $priv_key root@$worker_ip "mkdir -p /opt/cni/bin && tar -zxf - --no-same-owner -C /opt/cni/bin/" < $cni_plugins_binary

echo "Done copying binaries"
