#!/usr/bin/env bash

set -e

long_opts=priv-key:,worker-ip:,crictl-download:,crictl-binary:,runc-download:,runc-binary:,\
cni-plugins-download:,cni-plugins-binary:
script_name=$(basename "$0")
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

priv_key=
worker_ip=
crictl_download=
crictl_binary=
runc_download=
runc_binary=
cni_plugins_download=
cni_plugins_binary=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --priv-key)
        priv_key=$(opt_val "$2")
        shift 2
        ;;
      --worker-ip)
        worker_ip=$(opt_val "$2")
        shift 2
        ;;
      --crictl-download)
        crictl_download=$(opt_val "$2")
        shift 2
        ;;
      --crictl-binary)
        crictl_binary=$(opt_val "$2")
        shift 2
        ;;
      --runc-download)
        runc_download=$(opt_val "$2")
        shift 2
        ;;
      --runc-binary)
        runc_binary=$(opt_val "$2")
        shift 2
        ;;
      --cni-plugins-download)
        cni_plugins_download=$(opt_val "$2")
        shift 2
        ;;
      --cni-plugins-binary)
        cni_plugins_binary=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

crictl_binary_actual=$(xec make-download-path\
 --download-url=$crictl_download --download-path=$crictl_binary)
runc_binary_actual=$(xec make-download-path\
 --download-url=$runc_download --download-path=$runc_binary)
cni_plugins_binary_actual=$(xec make-download-path\
 --download-url=$cni_plugins_download --download-path=$cni_plugins_binary)

# debug
#echo "priv_key=$priv_key"
#echo "worker_ip=$worker_ip"
#echo "crictl_download=$crictl_download"
#echo "crictl_binary=$crictl_binary"
#echo "crictl_binary_actual=$crictl_binary_actual"
#echo "runc_download=$runc_download"
#echo "runc_binary=$runc_binary"
#echo "runc_binary_actual=$runc_binary_actual"
#echo "cni_plugins_download=$cni_plugins_download"
#echo "cni_plugins_binary=$cni_plugins_binary"
#echo "cni_plugins_binary_actual=$cni_plugins_binary_actual"

echo "Copying misc kubernetes binaries"

xec download-obj --url="$crictl_download" --dest="$crictl_binary_actual"
echo "Copying crictl binary to worker"
cat $crictl_binary_actual | ssh -i $priv_key root@$worker_ip\
 "tar zxvf - --no-same-owner -C /usr/local/bin/ crictl && chmod +x /usr/local/bin/crictl"

xec download-obj --url="$runc_download" --dest="$runc_binary_actual" --executable
echo "Copying runc binary to worker"
scp -i $priv_key $runc_binary_actual root@$worker_ip:/usr/local/bin/

xec download-obj --url="$cni_plugins_download" --dest="$cni_plugins_binary_actual"
echo "Copying cni plugins binary to worker"
ssh -i $priv_key root@$worker_ip "mkdir -p /opt/cni/bin"
cat $cni_plugins_binary_actual | ssh -i $priv_key root@$worker_ip "tar zxvf - --no-same-owner -C /opt/cni/bin/"

echo "Done copying binaries"
