#!/usr/bin/env bash

set -e

long_opts=priv-key:,worker-ip:,crictl-binary:,runc-binary:,cni-plugins-binary:
script_name=$(basename "$0")
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

priv_key=
worker_ip=
crictl_binary=
runc_binary=
cni_plugins_binary=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --priv-key)
        priv_key=$(opt_val "$2")
        shift 2
        ;;
      --worker-ip)
        worker_ip=$(opt_val "$2")
        shift 2
        ;;
      --crictl-binary)
        crictl_binary=$(opt_val "$2")
        shift 2
        ;;
      --runc-binary)
        runc_binary=$(opt_val "$2")
        shift 2
        ;;
      --cni-plugins-binary)
        cni_plugins_binary=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

echo "Copying misc kubernetes binaries"

echo "Copying crictl binary to worker"
cat $crictl_binary | ssh -i $priv_key root@$worker_ip\
 "tar zxvf - --no-same-owner -C /usr/local/bin/ crictl && chmod +x /usr/local/bin/crictl"

echo "Copying runc binary to worker"
scp -i $priv_key $runc_binary root@$worker_ip:/usr/local/bin/runc

echo "Copying cni plugins binary to worker"
ssh -i $priv_key root@$worker_ip "mkdir -p /opt/cni/bin"
cat $cni_plugins_binary | ssh -i $priv_key root@$worker_ip "tar zxvf - --no-same-owner -C /opt/cni/bin/"

echo "Done copying binaries"
