#!/usr/bin/env bash

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# this worked:
#virt-install\
#  --name kvmtest\
#  --memory 2048\
#  --vcpus 2\
#  --disk size=30\
#  --cdrom $script_dir/../binaries/CentOS-Stream-8-x86_64-latest-dvd1.iso\
#  --os-variant centos-stream8

# next to try
virt-install --debug\
  --name kvmtest\
  --memory 2048\
  --vcpus 2\
  --disk size=30\
  --cdrom $script_dir/../binaries/CentOS-Stream-8-x86_64-latest-dvd1.iso\
  --location $script_dir/../binaries/CentOS-Stream-8-x86_64-latest-dvd1.iso\
  --boot hd,cdrom\
  --os-variant centos-stream8\
  --initrd-inject $script_dir/ks.cfg\
  --extra-args="ks=file:/ks.cfg console=tty0 console=ttyS0,115200n8"




#  --network default\
#  --location $script_dir/../binaries/CentOS-Stream-8-x86_64-latest-dvd1.iso\
#  --osinfo detect=on,require=on\
#  --graphics none\
#  --os-variant centos-stream8


#  --initrd-inject $script_dir/ks.cfg\
#  --extra-args="ks=file:$script_dir/ks.cfg console=tty0 console=ttyS0,115200n8"\
  