apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: nodeport
        port: 30011
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage:
      type: persistent-claim
      size: 2Gi
      #selector:
      #  pv: kafka-pv
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
      #selector:
      #  pv: zookeeper-pv
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    logging: debug
    enableSaramaLogging: true
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5