#!/usr/bin/env bash
#
# Helm-installs Open EBS.
#

config=$1

OPENEBS_VER=4.4.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)

url=https://openebs.github.io/dynamic-localpv-provisioner/localpv-provisioner-$OPENEBS_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

helm upgrade --install openebs $tgz\
  --namespace openebs\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  --wait
