#!/usr/bin/env bash

config=$1

OPENEBS_VER=3.10.0

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)

url=https://github.com/openebs/charts/releases/download/openebs-$OPENEBS_VER/openebs-$OPENEBS_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

helm install openebs\
  --namespace openebs\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  $tgz
