#!/usr/bin/env bash
#
# Generates TLS cert/key and kubeconfig for the various components:
# - kube-proxy
# - kubelet
# - kube-controller-manager
# - kube-scheduler
# - admin (the admin kubeconfig allows the script (and you) to access the cluster API)
#

set -e

long_opts=host-name:,host-ip:,subject-org:,subject-cn:,kubeconfig-name:,\
csr-type:,controller-ip:,ca-cert:,ca-key:

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

host_name=
host_ip=
subject_org=
subject_cn=
kubeconfig_name=
csr_type=
ca_cert=
ca_key=
controller_ip=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

echo "creating generated/kubeconfig/$kubeconfig_name.kubeconfig"
tmp_dir=$(mktemp -d)

if [[ "$csr_type" == altnames ]]; then
  sed -e "s/HOSTNAME/$host_name/g"\
      -e "s/IPADDRESS/$host_ip/g"\
      -e "s/ORGANIZATION/$subject_org/g"\
      -e "s/COMMONNAME/$subject_cn/g"\
      $script_dir/csr.altnames.conf >| $tmp_dir/csr.conf
elif [[ "$csr_type" == simple ]]; then
  sed -e "s/ORGANIZATION/$subject_org/g"\
      -e "s/COMMONNAME/$subject_cn/g"\
      $script_dir/csr.conf >| $tmp_dir/csr.conf
fi

subject="/CN=$subject_cn"
if [[ -n "$subject_org" ]]; then
  subject="/O=$subject_org/CN=$subject_cn"
fi

if [[ -n "$csr_type" ]]; then
  openssl genrsa\
    -out $DTKBASE/generated/cert/$kubeconfig_name-key.pem\
    2048

  openssl req\
    -new\
    -key $DTKBASE/generated/cert/$kubeconfig_name-key.pem\
    -out $tmp_dir/$kubeconfig_name.csr\
    -config $tmp_dir/csr.conf\
    2>/dev/null

  openssl x509\
    -req\
    -in $tmp_dir/$kubeconfig_name.csr\
    -CA $ca_cert\
    -CAkey $ca_key\
    -CAcreateserial\
    -out $DTKBASE/generated/cert/$kubeconfig_name.pem\
    -days 10000\
    -extensions v3_ext\
    -extfile $tmp_dir/csr.conf\
    2>/dev/null
else
  openssl req\
    -newkey rsa:2048\
    -nodes\
    -keyout $DTKBASE/generated/cert/$kubeconfig_name-key.pem\
    -subj $subject\
    -out $tmp_dir/$kubeconfig_name.csr\
    2>/dev/null

  openssl x509\
    -req\
    -in $tmp_dir/$kubeconfig_name.csr\
    -CA $ca_cert\
    -CAkey $ca_key\
    -CAcreateserial\
    -sha256\
    -out $DTKBASE/generated/cert/$kubeconfig_name.pem\
    -days 10000\
    2>/dev/null
fi

kubectl config set-cluster kubernetes\
  --certificate-authority=$ca_cert\
  --embed-certs=true\
  --server=https://$controller_ip:6443\
  --kubeconfig=$DTKBASE/generated/kubeconfig/$kubeconfig_name.kubeconfig

kubectl config set-credentials $subject_cn\
  --client-certificate=$DTKBASE/generated/cert/$kubeconfig_name.pem\
  --client-key=$DTKBASE/generated/cert/$kubeconfig_name-key.pem\
  --embed-certs=true\
  --kubeconfig=$DTKBASE/generated/kubeconfig/$kubeconfig_name.kubeconfig

kubectl config set-context default\
  --cluster=kubernetes\
  --user=$subject_cn\
  --kubeconfig=$DTKBASE/generated/kubeconfig/$kubeconfig_name.kubeconfig

kubectl config use-context default\
  --kubeconfig=$DTKBASE/generated/kubeconfig/$kubeconfig_name.kubeconfig

rm -rf $tmp_dir
