apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver
    command:
    - kube-apiserver
    - --advertise-address=CONTROLLER_IP
    - --allow-privileged=true
    - --apiserver-count=3
    - --audit-log-maxage=30
    - --audit-log-maxbackup=3
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/audit.log
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/var/lib/kubernetes/ca.pem
    - --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --enable-aggregator-routing=true
    - --encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml
    - --etcd-cafile=/var/lib/kubernetes/ca.pem
    - --etcd-certfile=/var/lib/kubernetes/kubernetes.pem
    - --etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem
    - --etcd-servers=https://CONTROLLER_IP:2379
    - --event-ttl=1h
    - --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem
    - --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem
    - --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem
    - --proxy-client-cert-file=/var/lib/kubernetes/aggregator.pem
    - --proxy-client-key-file=/var/lib/kubernetes/aggregator-key.pem
    - --requestheader-allowed-names=aggregator
    - --requestheader-client-ca-file=/var/lib/kubernetes/ca.pem
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --runtime-config=api/all=true
    - --service-account-issuer=https://kubernetes.default.svc
    - --service-account-key-file=/var/lib/kubernetes/service-account-key.pem
    - --service-account-signing-key-file=/var/lib/kubernetes/service-account-key.pem
    - --service-cluster-ip-range=10.32.0.0/24
    - --service-node-port-range=30000-32767
    - --tls-cert-file=/var/lib/kubernetes/kubernetes.pem
    - --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem
    - --v=2
    image: k8s.gcr.io/kube-apiserver:v1.25.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
    securityContext:
      privileged: false
    volumeMounts:
    - name: d1
      mountPath: /var/lib/kubernetes/
      readOnly: true
    - name: d2
      mountPath: /var/log
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: d1
    hostPath:
      path: /var/lib/kubernetes/
      type: DirectoryOrCreate
  - name: d2
    hostPath:
      path: /var/log
      type: DirectoryOrCreate
