# Tests the installation of the Nginx Gateway Fabric add-on
---
apiVersion: v1
kind: Namespace
metadata:
  name: gw-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-test
  namespace: gw-test
data:
  server.py: |
    from http.server import BaseHTTPRequestHandler, HTTPServer

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header('Content-Type', 'text/html')
            self.end_headers()
            self.wfile.write(b"hello, world\n")

        def log_message(self, format, *args):
            print(f"{self.address_string()} - {format % args}", flush=True)

    print("Starting gw-test server on port 8080...", flush=True)
    HTTPServer(('0.0.0.0', 8080), Handler).serve_forever()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-test
  namespace: gw-test
spec:
  selector:
    matchLabels:
      app: gw-test
  replicas: 1
  template:
    metadata:
      labels:
        app: gw-test
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: gw-test
          image: python:3.11-slim
          command:
            - python
          args:
            - /app/server.py
          volumeMounts:
            - name: gw-test
              mountPath: /app
          ports:
          - name: gw-test
            containerPort: 8080
      volumes:
        - name: gw-test
          configMap:
            name: gw-test
---
apiVersion: v1
kind: Service
metadata:
  name: gw-test
  namespace: gw-test
spec:
  selector:
    app: gw-test
  ports:
  - name: gw-test
    port: 8080
    targetPort: gw-test
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gw-test
  namespace: gw-test
spec:
  parentRefs:
  - name: dtk-gateway
    namespace: nginx-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /gw-test
    backendRefs:
    - name: gw-test
      port: 8080
