#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../scripts" && pwd)"
"$script_dir"/install-guest-additions\
 --template-vmname=bingo\
 --guest-additions-path=/home/eace/k8sbyhand/newroot/media/VBoxGuestAdditions_6.1.14.iso