#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/worker/kube-router/install-kube-router\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --controller-ip=192.168.0.81\
 --worker-ip=192.168.0.85\
 --kube-router-yaml-download=\
 --kube-router-yaml=$proj_root/binaries/generic-kuberouter-all-features.yaml\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig

#proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
#$proj_root/worker/kube-router/install-kube-router\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --controller-ip=192.168.0.??\
# --worker-ip=192.168.0.??\
# --kube-router-yaml-download=https://raw.githubusercontent.com/cloudnativelabs/kube-router/v1.1.1/daemonset/generic-kuberouter-all-features.yaml\
# --kube-router-yaml=$proj_root/binaries\
# --admin-kubeconfig=$proj_root/admin/admin.kubeconfig
