#!/usr/bin/env bash

# this test does not provide download paths so - they go to media
./kuvbxctl\
 --create-template-vm\
 --template-vmname=foobar\
 --centos-iso-path=/home/eace/k8sbyhand/newroot/media/CentOS-8.2.2004-x86_64-dvd1.iso\
 --guest-additions-path=/home/eace/k8sbyhand/newroot/media/VBoxGuestAdditions_6.1.14.iso\
 --host-network-interface=enp0s31f6\
 --vboxdir=/sdb1/virtualbox/
