#!/usr/bin/env bash

#
# Generates tls/kubernetes.pem amd kubernetes-key.pem. Uses tls/ca.pem and ca-key.pem which are generated
# by scripts/gen-root-ca
#

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

$proj_root/scripts/gen-cluster-tls\
  --controller-ip=192.168.0.81\
  --ca-cert=$proj_root/tls/ca.pem\
  --ca-key=$proj_root/tls/ca-key.pem
