#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

$proj_root/scripts/install-guest-additions\
 --template-vmname=bingo\
 --guest-additions-path=$proj_root/media/VBoxGuestAdditions_6.1.14.iso