#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/scripts/install-etcd\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --controller-ip=192.168.0.81\
 --controller-hostname=doc\
 --etcd-gzip=$proj_root/binaries/etcd-v3.4.14-linux-amd64.tar.gz\
 --kubernetes-cert=$proj_root/tls/kubernetes.pem\
 --kubernetes-key=$proj_root/tls/kubernetes-key.pem\
 --ca-cert=$proj_root/tls/ca.pem

#$proj_root/scripts/install-etcd\
# --priv-key=$proj_root/kickstart/id_ed25519\
# --controller-ip=192.168.0.ZZZ\
# --controller-hostname=doc\
# --etcd-download=https://github.com/etcd-io/etcd/releases/download/v3.4.14/etcd-v3.4.14-linux-amd64.tar.gz\
# --etcd-gzip=$proj_root/binaries\
# --kubernetes-cert=$proj_root/tls/kubernetes.pem\
# --kubernetes-key=$proj_root/tls/kubernetes-key.pem\
# --ca-cert=$proj_root/tls/ca.pem

