#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/kuvboxctl\
 --template-vmname=bingo\
 --vboxdir=/sdb1/virtualbox\
 --controller=vmname=doc,memory=4096,cpus=2\
 --worker=vmname=ham,memory=4096,cpus=2\
 --worker=vmname=monk,memory=4096,cpus=2
