#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
$proj_root/dns/coredns/install-coredns\
 --replicas=1\
 --admin-kubeconfig=$proj_root/admin/admin.kubeconfig

#$proj_root/dns/coredns/install-coredns\
# --replicas=1\
# --admin-kubeconfig=$proj_root/admin/admin.kubeconfig
