#!/usr/bin/env bash

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

$proj_root/scripts/create-vm\
 --template-vmname=bingo\
 --centos-iso-path=$proj_root/media/CentOS-8.2.2004-x86_64-dvd1.iso\
 --kickstart-iso-path=$proj_root/media/kickstart.iso\
 --host-network-interface=enp0s31f6\
 --vboxdir=/sdb1/virtualbox
