#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../control-plane/kube-scheduler" && pwd)"
"$script_dir"/install-kube-scheduler\
 --priv-key=/home/eace/k8sbyhand/newroot/kickstart/id_ed25519\
 --controller-ip=192.168.0.81\
 --controller-hostname=doc\
 --kube-scheduler-binary=/home/eace/k8sbyhand/newroot/binaries/kube-scheduler\
 --kubernetes-cert=/home/eace/k8sbyhand/newroot/tls/kubernetes.pem\
 --kubernetes-key=/home/eace/k8sbyhand/newroot/tls/kubernetes-key.pem\
 --ca-cert=/home/eace/k8sbyhand/newroot/tls/ca.pem\
 --ca-key=/home/eace/k8sbyhand/newroot/tls/ca-key.pem

#script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../control-plane/kube-scheduler" && pwd)"
#"$script_dir"/install-kube-scheduler\
# --priv-key=/home/eace/k8sbyhand/newroot/kickstart/id_ed25519\
# --controller-ip=192.168.0.ZZZ\
# --controller-hostname=doc\
# --kube-scheduler-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-scheduler\
# --kube-scheduler-binary=/home/eace/k8sbyhand/newroot/binaries\
# --kubernetes-cert=/home/eace/k8sbyhand/newroot/tls/kubernetes.pem\
# --kubernetes-key=/home/eace/k8sbyhand/newroot/tls/kubernetes-key.pem\
# --ca-cert=/home/eace/k8sbyhand/newroot/tls/ca.pem\
# --ca-key=/home/eace/k8sbyhand/newroot/tls/ca-key.pem
