#!/usr/bin/env bash

# Creates a clone VM from the passed template VM. The cloned VM will have the passed
# characteristics (VM name, mem, etc.)

set -e

long_opts=priv-key:,template-vmname:,clone-vmname:,clone-ram:,clone-cpus:,vboxdir:
script_name=$(basename "$0")
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

priv_key=
template_vmname=
clone_vmname=
clone_ram=
clone_cpus=
vboxdir=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --priv-key)
        priv_key=$(opt_val "$2")
        shift 2
        ;;
	    --template-vmname)
        template_vmname=$(opt_val "$2")
        shift 2
        ;;
      --clone-vmname)
        clone_vmname=$(opt_val "$2")
        shift 2
        ;;
      --clone-ram)
        clone_ram=$(opt_val "$2")
        shift 2
        ;;
      --clone-cpus)
        clone_cpus=$(opt_val "$2")
        shift 2
        ;;
      --vboxdir)
        vboxdir=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

# debug
#echo "priv_key=$priv_key"
#echo "template_vmname=$template_vmname"
#echo "clone_vmname=$clone_vmname"
#echo "clone_ram=$clone_ram"
#echo "clone_cpus=$clone_cpus"
#echo "vboxdir=$vboxdir"

echo "cloning VM \"$clone_vmname\" from template VM \"$template_vmname\""
VBoxManage clonevm $template_vmname\
 --basefolder="$vboxdir"\
 --mode=machine\
 --name=$clone_vmname\
 --register

echo "setting VM characteristics"
VBoxManage modifyvm $clone_vmname\
 --cpus $clone_cpus\
 --memory $clone_ram\

echo "starting cloned VM"
VBoxManage startvm $clone_vmname

echo "getting IP address from cloned VM"
clone_ip=$($proj_root/scripts/get-vm-ip $clone_vmname)

echo "changing the hostname for cloned VM"
ssh -o "StrictHostKeyChecking no" -i $priv_key root@$clone_ip "hostnamectl set-hostname $clone_vmname"

echo "shutting down cloned VM"
VBoxManage controlvm $clone_vmname acpipowerbutton
$proj_root/scripts/wait-vm $clone_vmname --stopped

# virtual box needs a moment or subsequent vboxmanage commands seem to intermittently error
sleep 5s

echo "done cloning \"$clone_vmname\""
