#!/usr/bin/env bash

# this script sizes the storage of a VM up. It assumes the storage was configured by the kickstart
# script. If you change the kickstart partitioning then you may need to modify this.

# create /dev/sda3
printf 'n\np\n3\n\n\nt\n3\n8e\nw' | fdisk /dev/sda
partprobe

# create pv
pvcreate /dev/sda3

# extend lv to include pv
vg=$(vgs --noheadings | awk '{print $1}')
vgextend $vg /dev/sda3

# extend lv to use space added to vg
size=$(vgdisplay | grep Free | awk '{print $5}')
lvextend -l +$size /dev/cl_cloneme/root

# resize filesystem
xfs_growfs /dev/cl_cloneme/root