#!/usr/bin/env bash

set -e

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

priv_key=$1
shift

echo "To access the cluster node(s) via ssh:"
echo

for vm in "$@"
do
  ip=$($proj_root/scripts/get-vm-ip $vm)
  echo "$vm: ssh -i $priv_key root@$ip"
done
