#!/usr/bin/env bash

mismatch=0
tested_openssl_version="1.1.1f"
tested_genisoimage_version="1.1.11"
tested_vboxmanage_version="6.1.30"
tested_ssh_version="OpenSSH_8.2p1"
tested_host_os_version="Ubuntu 20.04.4 LTS"
tested_kubectl_version="v1.23.4"
tested_curl_version="7.68.0"

if which openssl &>/dev/null; then
  openssl_version=$(openssl version | awk '{print $2}')
  [[ $openssl_version == "$tested_openssl_version" ]] && openssl_ok=Yes || { openssl_ok=No; mismatch=1; }
else
  openssl_version="not found"
fi

if which genisoimage &>/dev/null; then
  genisoimage_version=$(genisoimage --version | awk '{print $2}')
  [[ $genisoimage_version == "$tested_genisoimage_version" ]] && genisoimage_ok=Yes || { genisoimage_ok=No; mismatch=1; }
else
  genisoimage_version="not found"
fi

if which vboxmanage &>/dev/null; then
  vboxmanage_version=$(vboxmanage --version)
  [[ $vboxmanage_version == $tested_vboxmanage_version* ]] && vboxmanage_ok=Yes || { vboxmanage_ok=No; mismatch=1; }
else
  vboxmanage_version="not found"
fi

if which ssh &>/dev/null; then
  ssh_version=$(ssh -V 2> >(awk '{print $1}'))
  [[ $ssh_version == "$tested_ssh_version" ]] && ssh_ok=Yes || { ssh_ok=No; mismatch=1; }
else
  ssh_version="not found"
fi

if which lsb_release &>/dev/null; then
  host_os_version=$(lsb_release -a 2>/dev/null | grep Description | cut -d: -f2- | xargs)
  [[ $host_os_version == "$tested_host_os_version" ]] && os_ok=Yes || { os_ok=No; mismatch=1; }
else
  host_os_version="unable to determine"
fi

if which kubectl &>/dev/null; then
  kubectl_version=$(kubectl version --short --client | cut -d: -f2- | xargs)
  [[ $kubectl_version == "$tested_kubectl_version" ]] && kubectl_ok=Yes || { kubectl_ok=No; mismatch=1; }
else
  kubectl_version="not found"
fi

if which curl &>/dev/null; then
  curl_version=$(curl --version |  head -n1 | awk '{print $2}')
  [[ $curl_version == "$tested_curl_version" ]] && curl_ok=Yes || { curl_ok=No; mismatch=1; }
else
  curl_version="not found"
fi

cat <<EOF | column -t -s "|"
component|tested|found|matches?
---------|------|-----|--------
openssl|$tested_openssl_version|$openssl_version|$openssl_ok
openssh|$tested_ssh_version|$ssh_version|$ssh_ok
genisoimage|$tested_genisoimage_version|$genisoimage_version|$genisoimage_ok
virtual box|$tested_vboxmanage_version|$vboxmanage_version|$vboxmanage_ok
host operating system|$tested_host_os_version|$host_os_version|$os_ok
kubectl (client only)|$tested_kubectl_version|$kubectl_version|$kubectl_ok
curl|$tested_curl_version|$curl_version|$curl_ok
EOF

if [[ $mismatch -ne 0 ]]; then
  echo; echo "WARNING: Found mismatches between the tested configuration and your configuration"
  exit 1
fi
