#!/usr/bin/env bash
#
# Creates an ISO from the script directory and writes the ISO into the project 'generated/kickstart'
# directory. Expects the name of a kickstart config file in arg 1 in the same directory as the script.
#

set -e

kickstart=$1

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp $script_dir/desktop-kubernetes.service $script_dir/desktop-kubernetes.sh $DTKBASE/generated/kickstart
cp $script_dir/$kickstart $DTKBASE/generated/kickstart/ks.cfg

rm -f $DTKBASE/generated/iso/kickstart.iso
genisoimage -J -R -input-charset utf-8 -volid OEMDRV -o $DTKBASE/generated/iso/kickstart.iso $DTKBASE/generated/kickstart
