#!/usr/bin/env bash
#
# Creates an ISO from the script directory and writes the ISO into the project '$GENERATED/kickstart'
# directory. Expects the name of a kickstart config file in arg 1 in the same directory as the script.
#

set -e

kickstart=$1

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp $script_dir/desktop-kubernetes.service $script_dir/desktop-kubernetes.sh $DTKBASE/$GENERATED/kickstart
cp $DTKBASE/kickstarts/$kickstart $DTKBASE/$GENERATED/kickstart/ks.cfg

rm -f $DTKBASE/$GENERATED/iso/kickstart.iso
genisoimage -J -R -input-charset utf-8 -volid OEMDRV -o $DTKBASE/$GENERATED/iso/kickstart.iso $DTKBASE/$GENERATED/kickstart
