#!/usr/bin/env bash
#
# Gets the IP address from a VM using Guest Additions functionality. (Obviously requires that Guest Additions are
# installed in the guest.) The project supports provisioning a cluster in either bridged - or host only - network
# mode. In bridged mode: enp0s3 is bridged, providing host-to-guest, guest-to-guest, and guest-to-internet. In
# host only mode: enp0s3 is a NAT network for internet access from the guest and enp0s8 is the host only NIC
# for host-to-guest, and guest-to-guest. This script handles those two cases.
#
# The script blocks (forever) trying to get the IP address. Handles the case where you're using this to make
# sure the guest VM started.
#
if [[ "$#" -ne 1 ]]; then
  echo "only one arg allowed: the VM name. E.g. 'get-vm-ip my-vm-name"
  exit 1
fi

vm="$1"

netnum=

while [[ -z $netnum ]]; do
  for interface in 0 1; do
    netname=$(VBoxManage guestproperty get "$vm" "/VirtualBox/GuestInfo/Net/$interface/Name" 2>/dev/null | awk '{print $2}')
    if [[ $netname == "enp0s3" ]]; then
      netnum=$interface
    elif [[ $netname == "enp0s8" ]]; then
      netnum=$interface
      # if we find enp0s8 we're done
      break
    fi
  done
done

ip=$(VBoxManage guestproperty get "$vm" "/VirtualBox/GuestInfo/Net/$netnum/V4/IP" 2>/dev/null)

echo "$ip" | awk '{print $2}'
