#!/usr/bin/env bash
#
# Installs guest additions which enables getting the IP address. Mounts the guest additions
# ISO and boots the VM. On boot, the desktop-kubernetes service that was installed by the
# kickstart script will run, and install the guest additions unattended, booting the VM when
# needed. To watch the guest additions being installed, you can log into the VM, open a
# terminal, and: 'journalctl -u desktop-kubernetes -f'. Upon return from this script, the
# guest additions install has completed, the VM is shut down, and the guest additions ISO
# is detached.
#

set -e

long_opts=template-vmname:,guest-additions-path:
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

template_vmname=
guest_additions_path=

if ! parsed=$(xec parseargs $long_opts "$@"); then
  echo "$parsed"
  exit 1
fi
eval $(echo -e "$parsed")

# attach guest additions ISO and set boot from disk
VBoxManage storageattach $template_vmname --storagectl IDE --port 0 --device 0 --type dvddrive\
 --medium $guest_additions_path
VBoxManage modifyvm $template_vmname --boot1 disk --boot2 none --boot3 none --boot4 none

# If successful it will be possible to get the IP address from the VM
echo "starting VM to begin guest additions installation"
VBoxManage startvm $template_vmname

echo "waiting for the VM to start and install guest additions"
$script_dir/wait-vm $template_vmname --started

echo "waiting for the VM to stop - the guest additions install script performs a shutdown when it is done"
$script_dir/wait-vm $template_vmname --stopped
sleep 5s

echo "detaching guest additions ISO"
VBoxManage storageattach $template_vmname --storagectl IDE --port 0 --device 0 --medium none
