#!/usr/bin/env bash
#
# Starts / stops / deletes a cluster. Usage:
#
# up-down-del <up|down|del> <config>
#
# E.g.:
#
# up-down-del up ~/my-config.yaml
#

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

op="$1"
config="$2"

yq -r '.vms[].name' "$config" | while read vmname; do
  case $op in
    up)
      VBoxManage startvm $vm
      sleep 5s
      ;;
    down)
      VBoxManage controlvm $vm acpipowerbutton
      $script_dir/wait-vm $vm --stopped
      ;;
    del)
      VBoxManage controlvm $vm poweroff &>/dev/null && $script_dir/wait-vm $vm --stopped || echo "(not running)"
      sleep 5s
      VBoxManage unregistervm $vm --delete
      ;;
  esac
done