#!/usr/bin/env bash

# TODO TEST ME
set -e

proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Checks installed versions of tools used by this project against tested versions. Comment out
# if variances will not cause problems
$proj_root/scripts/verify-prereqs

echo "downloading CentOS and Guest Additions ISOs and creating a template VM from them"
$proj_root/scripts/create-template-vm\
 --template-vmname=bingo\
 --centos-iso-download=http://mirror.umd.edu/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso\
 --centos-iso-path=$proj_root/media\
 --guest-additions-download=http://download.virtualbox.org/virtualbox/6.1.14/VBoxGuestAdditions_6.1.14.iso\
 --guest-additions-path=$proj_root/media\
 --host-network-interface=enp0s31f6\
 --vboxdir=/sdb1/virtualbox

echo "generating root CA into tls directory on this machine"
$proj_root/scripts/gen-root-ca

echo "provisioning a controller node"
$proj_root/toplevel-scripts/provision-controller\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --template-vmname=bingo\
 --vboxdir=/sdb1/virtualbox\
 --controller-hostname=doc\
 --controller-ram=4096\
 --controller-cpu=2\
 --etcd-download=https://github.com/etcd-io/etcd/releases/download/v3.4.14/etcd-v3.4.14-linux-amd64.tar.gz\
 --etcd-gzip=$proj_root/binaries\
 --kube-apiserver-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-apiserver\
 --kube-apiserver-binary=$proj_root/binaries\
 --kube-controller-manager-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-controller-manager\
 --kube-controller-manager-binary=$proj_root/binaries\
 --kube-scheduler-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-scheduler\
 --kube-scheduler-binary=$proj_root/binaries\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem\

echo "provisioning worker nodes"
controller_ip=$($proj_root/scripts/get-vm-ip doc)
$proj_root/toplevel-scripts/provision-workers\
 --worker=ham,4096,2\
 --worker=monk,8192,3\
 --controller-ip=$controller_ip\
 --controller-hostname=doc\
 --template-vmname=bingo\
 --vboxdir=/sdb1/virtualbox\
 --priv-key=$proj_root/kickstart/id_ed25519\
 --crictl-download=https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.19.0/crictl-v1.19.0-linux-amd64.tar.gz\
 --crictl-binary=$proj_root/binaries\
 --runc-download=https://github.com/opencontainers/runc/releases/download/v1.0.0-rc92/runc.amd64\
 --runc-binary=$proj_root/binaries/runc\
 --cni-plugins-download=https://github.com/containernetworking/plugins/releases/download/v0.9.0/cni-plugins-linux-amd64-v0.9.0.tgz\
 --cni-plugins-binary=$proj_root/binaries\
 --containerd-download=https://github.com/containerd/containerd/releases/download/v1.4.3/containerd-1.4.3-linux-amd64.tar.gz\
 --containerd-binary=$proj_root/binaries
 --kubelet-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubelet\
 --kubelet-binary=$proj_root/binaries\
 --kube-router-yaml-download=https://raw.githubusercontent.com/cloudnativelabs/kube-router/v1.1.1/daemonset/generic-kuberouter-all-features.yaml\
 --kube-router-yaml=$proj_root/binaries\
 --ca-cert=$proj_root/tls/ca.pem\
 --ca-key=$proj_root/tls/ca-key.pem\
