#!/usr/bin/env bash

set -e

long_opts=template-vmname:,clone-vmname:,clone-ram:,clone-cpus:,vboxdir:
script_name=$(basename "$0")
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

template_vmname=
clone_vmname=
clone_ram=
clone_cpus=
vboxdir=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
	    --template-vmname)
        template_vmname=$(opt_val "$2")
        shift 2
        ;;
      --clone-vmname)
        clone_vmname=$(opt_val "$2")
        shift 2
        ;;
      --clone-ram)
        clone_ram=$(opt_val "$2")
        shift 2
        ;;
      --clone-cpus)
        clone_cpus=$(opt_val "$2")
        shift 2
        ;;
      --vboxdir)
        vboxdir=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"
# todo validate args

# debug
#echo "template_vmname=$template_vmname"
#echo "clone_vmname=$clone_vmname"
#echo "clone_ram=$clone_ram"
#echo "clone_cpus=$clone_cpus"
#echo "vboxdir=$vboxdir"

echo "Cloning VM"
VBoxManage clonevm $template_vmname\
 --basefolder="$vboxdir"\
 --mode=machine\
 --name=$clone_vmname\
 --register

VBoxManage modifyvm $clone_vmname\
 --cpus $clone_cpus\
 --memory $clone_ram\

echo "Starting cloned VM to set the hostname"
VBoxManage startvm $clone_vmname

echo "Getting VM IP cloned VM $clone_vmname"
ip=$("$script_dir"/get-vm-ip $clone_vmname)

# run the SSH cmd in the background (on the desktop) or SSH will hang when the machine is powered off
echo "Changing the hostname for VM $clone_vmname"
kickstart_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../kickstart" && pwd)"
ssh -o "StrictHostKeyChecking no" -i $kickstart_dir/id_ed25519 root@$ip "hostnamectl set-hostname $clone_vmname && poweroff -f" &

# wait for the VM  to be stopped
"$script_dir"/wait-vm $clone_vmname --stopped

echo "Done cloning \"$template_vmname\" to \"$clone_vmname\""
