#!/usr/bin/env bash

vmip="$1"
priv_key="$2"

if [[ "$3" == "--controller" ]]; then
  ssh -i "$priv_key" root@$vmip << EOF
    firewall-cmd --permanent --add-port=6443/tcp
    firewall-cmd --permanent --add-port=2379-2380/tcp
    firewall-cmd --permanent --add-port=10250/tcp
    firewall-cmd --permanent --add-port=10251/tcp
    firewall-cmd --permanent --add-port=10252/tcp
    systemctl restart firewalld
EOF
fi

if [[ "$3" == "--worker" ]]; then
  ssh -i "$priv_key" root@$vmip << EOF
    firewall-cmd --permanent --add-port=10250/tcp
    firewall-cmd --permanent --add-port=30000-32767/tcp
    systemctl restart firewalld
EOF
fi
