#!/usr/bin/env bash

# Firewall rules per:
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports

vmip="$1"
priv_key="$2"

if [[ "$3" == "--controller" ]]; then
  ssh -i "$priv_key" root@$vmip << EOF
    firewall-cmd --permanent --add-port=6443/tcp
    firewall-cmd --permanent --add-port=2379-2380/tcp
    firewall-cmd --permanent --add-port=10250/tcp
    firewall-cmd --permanent --add-port=10251/tcp
    firewall-cmd --permanent --add-port=10252/tcp
    systemctl restart firewalld
EOF
fi

# 53/UDP required for DNS add-on. Determined by enabling firewalld and logging denied connections
if [[ "$3" == "--worker" ]]; then
  ssh -i "$priv_key" root@$vmip << EOF
    firewall-cmd --permanent --add-port=10250/tcp
    firewall-cmd --permanent --add-port=30000-32767/tcp
    firewall-cmd --permanent --add-port=53/udp
    systemctl restart firewalld
EOF
fi
