#!/usr/bin/env bash

# Configures a worker node - expects a node already to have been cloned by the clone-vm function.

set -e

long_opts=controller-ip:,worker-hostname:,priv-key:,admin-kubeconfig:,crictl-download:,crictl-binary:,\
runc-download:,runc-binary:,cni-plugins-download:,cni-plugins-binary:,containerd-download:,containerd-binary:,\
ca-cert:,ca-key:
script_name=$(basename "$0")
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# api
controller_ip=
# hostname doubles for VM name here. The script will find a clone VM with this VirtualBox VM name
# and change the hostname to match, then gen all the worker components wired up to that host name (which then
# becomes a kubernetes node name)
worker_hostname=
priv_key=
admin_kubeconfig=
crictl_download=
crictl_binary=
runc_download=
runc_binary=
cni_plugins_download=
cni_plugins_binary=
containerd_download=
containerd_binary=
ca_cert=
ca_key=

# internal
worker_ip=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --controller-ip)
        controller_ip=$(opt_val "$2")
        shift 2
        ;;
      --worker-hostname)
        worker_hostname=$(opt_val "$2")
        shift 2
        ;;
      --priv-key)
        priv_key=$(opt_val "$2")
        shift 2
        ;;
      --admin-kubeconfig)
        admin_kubeconfig=$(opt_val "$2")
        shift 2
        ;;
      --crictl-download)
        crictl_download=$(opt_val "$2")
        shift 2
        ;;
      --crictl-binary)
        crictl_binary=$(opt_val "$2")
        shift 2
        ;;
      --runc-download)
        runc_download=$(opt_val "$2")
        shift 2
        ;;
      --runc-binary)
        runc_binary=$(opt_val "$2")
        shift 2
        ;;
      --cni-plugins-download)
        cni_plugins_download=$(opt_val "$2")
        shift 2
        ;;
      --cni-plugins-binary)
        cni_plugins_binary=$(opt_val "$2")
        shift 2
        ;;
      --containerd-download)
        containerd_download=$(opt_val "$2")
        shift 2
        ;;
      --containerd-binary)
        containerd_binary=$(opt_val "$2")
        shift 2
        ;;
      --ca-cert)
        ca_cert=$(opt_val "$2")
        shift 2
        ;;
      --ca-key)
        ca_key=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"
# todo validate args

# debug
echo "controller_ip=$controller_ip"
echo "worker_hostname=$worker_hostname"
echo "priv_key=$priv_key"
echo "admin_kubeconfig=$admin_kubeconfig"
echo "crictl_download=$crictl_download"
echo "crictl_binary=$crictl_binary"
echo "runc_download=$runc_download"
echo "runc_binary=$runc_binary"
echo "cni_plugins_download=$cni_plugins_download"
echo "cni_plugins_binary=$cni_plugins_binary"
echo "containerd_download=$containerd_download"
echo "containerd_binary=$containerd_binary"
echo "ca_cert=$ca_cert"
echo "ca_key=$ca_key"

run_count=$(VBoxManage list runningvms | awk '{print $1}' | grep -e'"'$worker_hostname'"' | wc -l)
if [[ $run_count -eq 0 ]]; then
  echo "Starting worker VM"
  VBoxManage startvm $worker_hostname
fi

echo "Getting IP address from running VM"
worker_ip=$($proj_root/scripts/get-vm-ip $worker_hostname)

echo "Making worker configuration changes"
# The socat binary enables support for the kubectl port-forward command. By default the kubelet
# will fail to start if swap is enabled so disable swap
ssh -i $priv_key root@$worker_ip << EOF
  yum -y install socat conntrack ipset
  [[ -z "$(swapon --show)" ]] || { swapoff -a; sed -i '/ swap /d' /etc/fstab; }
EOF

echo "Configuring firewall rules"
$proj_root/scripts/configure-firewall $worker_ip $priv_key --worker

echo "Generating TLS certs for the worker"
TODO move gen-worker-tls to scripts
TODO gen-worker-tls put certs in worker/tls
TODO make name $worker_hostname-pem and -key.pem
TODO mod install-kubelet to get named cert from tls dir

$proj_root/worker/kubelet/gen-worker-tls\
  --worker-ip=$worker_ip\
  --worker-hostname=$worker_hostname\
  --ca-cert=$ca_cert\
  --ca-key=$ca_key

echo "Copying misc. binaries to the worker"
$proj_root/worker/misc/install-misc-bins\
 --priv-key=$prov_key\
 --worker-ip=$worker_ip\
 --crictl-download=$crictl_download\
 --crictl-binary=$crictl_binary\
 --runc-download=$runc_download\
 --runc-binary=$runc_binary\
 --cni-plugins-download=$cni_plugins_download\
 --cni-plugins-binary=$cni_plugins_binary

echo "Installing containerd"
$proj_root/worker/containerd/install-containerd\
 --priv-key=$prov_key\
 --worker-ip=$worker_ip\
 --containerd-download=$containerd_download\
 --containerd-binary=$containerd_binary

echo "Installing the kubelet"
$proj_root/worker/kubelet/install-kubelet\
 --priv-key=$priv_key\
 --controller-ip=$controller_ip\
 --worker-ip=$worker_ip\
 --worker-hostname=$worker_hostname\
 --kubelet-download=$kubelet_download\
 --kubelet-binary=$kubelet_binary\
 --ca-cert=$ca_cert\
 --ca-key=$ca_key

ready_count=$(kubectl --kubeconfig $admin_kubeconfig get nodes | grep $worker_hostname | grep Ready | wc -l &>/dev/null)

if [[ "$ready_count" -ne 1 ]]; then
  echo "Unable to verify that the worker node was successfully configured"
  exit 1
fi

echo "No errors detected with worker installation"
