#!/usr/bin/env bash

set -e

long_opts=template-vmname:,centos-iso-path:,guest-additions-path:,host-network-interface:,vboxdir:
script_name=$(basename "$0")
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

template_vmname=
centos_iso_path=
guest_additions_path=
host_network_interface=
vboxdir=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  if [[ "$?" -ne 0 ]]; then
    exit 1
  fi

  eval set -- "$parsed"
  while true; do
    case "$1" in
	    --template-vmname)
        template_vmname=$(opt_val "$2")
        shift 2
        ;;
      --centos-iso-path)
        centos_iso_path=$(opt_val "$2")
        shift 2
        ;;
      --guest-additions-path)
        guest_additions_path=$(opt_val "$2")
        shift 2
        ;;
      --host-network-interface)
        host_network_interface=$(opt_val "$2")
        shift 2
        ;;
      --vboxdir)
        vboxdir=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

# debug
#echo "template_vmname=$template_vmname"
#echo "centos_iso_path=$centos_iso_path"
#echo "guest_additions_path=$guest_additions_path"
#echo "host_network_interface=$host_network_interface"
#echo "vboxdir=$vboxdir"

echo "Generate SSH keys -- the public key will be copied to the VM by the kickstart script"
$proj_root/scripts/gen-ssh-keyfiles

echo "Generate kickstart ISO"
$proj_root/scripts/gen-kickstart-iso

echo "Create VM"
kickstart_iso_path=$(realpath $proj_root/media/kickstart.iso)
$proj_root/scripts/create-vm --template-vmname=$template_vmname\
  --centos-iso-path=$centos_iso_path\
  --kickstart-iso-path=$kickstart_iso_path\
  --host-network-interface=$host_network_interface\
  --vboxdir=$vboxdir

echo "Install guest additions"
$proj_root/scripts/install-guest-additions\
 --template-vmname=$template_vmname\
 --guest-additions-path=$guest_additions_path
