#!/usr/bin/env bash

# generates 'worker.pem' and 'worker-key.pem' which are used in the configuration of the kubelet

set -e

long_opts=worker-ip:,worker-hostname:,ca-cert:,ca-key:
script_name=$(basename "$0")
proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

worker_ip=
worker_hostname=
ca_cert=
ca_key=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
	    --worker-ip)
        worker_ip=$(opt_val "$2")
        shift 2
        ;;
	    --worker-hostname)
        worker_hostname=$(opt_val "$2")
        shift 2
        ;;
      --ca-cert)
        ca_cert=$(opt_val "$2")
        shift 2
        ;;
      --ca-key)
        ca_key=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

# debug
#echo "worker_ip=$worker_ip"
#echo "worker_hostname=$worker_hostname"
#echo "ca_cert=$ca_cert"
#echo "ca_key=$ca_key"

# generate key
openssl genrsa -out $proj_root/worker/tls/worker-key.pem 2048

# generate a CSR conf with the worker IP address embedded
tmp_dir=$(mktemp -d)

# note the worker hostname and IP are in this CSR
cat <<EOF > $tmp_dir/worker-csr.conf
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
O = system:nodes
CN = system:node:$worker_hostname

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = $worker_hostname
IP.1 = $worker_ip

[ v3_ext ]
authorityKeyIdentifier=keyid,issuer:always
basicConstraints=CA:FALSE
keyUsage=keyEncipherment,dataEncipherment
extendedKeyUsage=serverAuth,clientAuth
subjectAltName=@alt_names
EOF

# create a CSR using the conf from above
openssl req -new -key $proj_root/worker/tls/worker-key.pem\
 -out $tmp_dir/worker.csr -config $tmp_dir/worker-csr.conf

# gen certificate using the ca cert and key provided to the script, and the csr from above
openssl x509 -req -in $tmp_dir/worker.csr -CA $ca_cert -CAkey $ca_key -CAcreateserial\
 -out $proj_root/worker/tls/worker.pem -days 10000 -extensions v3_ext -extfile $tmp_dir/worker-csr.conf

# cleanup
rm -rf $tmp_dir $proj_root/scripts/gen-worker-tls/ca.srl
