#!/usr/bin/env bash

# generates root CA cert and key

tls_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../tls" && pwd)"

openssl genrsa -out "$tls_dir/ca-key.pem" 2048
openssl req -x509 -new -nodes -key "$tls_dir/ca-key.pem" -sha256\
 -subj "/CN=internalca" -days 10000 -out "$tls_dir/ca.pem"
