#!/usr/bin/env bash

#
# a coding helper that reads a stdin list of script variable decls and generates long option parsing - and other
# lines of code - needed by a script to parse options. Assumes variable my_frobozz_val is passed as long opt
# --my-frobozz-val. E.g.:
#
# cat <<EOF | scripts/make-parse-args-code
# my_var_1=
# some_other_var=
# ting_tang=
# walla_walla=
# bing_bang=
# EOF
#

debug=("# debug")
long_opts="long_opts="
comma=""
while IFS='$\n' read -r line; do
  line="${line//=/}"
  foo="${line//_/-}"
  echo "      --$foo)"
  echo "        $line=\$(opt_val \"\$2\")"
  echo "        shift 2"
  echo "        ;;"
  debug+=("echo \"$line=\$$line\"")
  long_opts="$long_opts$comma$foo:"
  comma=","
done

for stmt in "${debug[@]}"; do
  echo $stmt
done

echo "$long_opts"