kind: EncryptionConfig
apiVersion: v1
resources:
- resources:
  - secrets
  providers:
  - aescbc:
      keys:
      - name: key1
        secret: F3dF5Hdp5AL7ZlK4zXfnk1EITI31ENFnFcfCg7Wf9vs=
  - identity: {}
