#!/usr/bin/env bash

config=$1

INGRESS_NGINX_VER=4.12.2

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
url=https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-$INGRESS_NGINX_VER/ingress-nginx-$INGRESS_NGINX_VER.tgz
tgz=$DTKBASE/binaries/$(basename $url)
xec download-obj --url=$url --dest=$tgz

ssl_passthrough=$(yq '.addons[] | select(.name == "ingress-nginx").ssl-passthrough' $config)
if [[ $ssl_passthrough == "true" ]]; then
  ssl_passthrough="--set controller.extraArgs.enable-ssl-passthrough="
else
  ssl_passthrough=""
fi

admin_kubeconfig=$(yq .cluster.admin-kubeconfig $config)
helm upgrade --install ingress-nginx\
  --namespace ingress-nginx\
  --create-namespace\
  --kubeconfig $admin_kubeconfig\
  --values $script_dir/values.yaml\
  $ssl_passthrough\
  $tgz
