#!/usr/bin/env bash
#
# Installs and configures the "Resource metrics pipeline" per:
# https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#resource-metrics-pipeline
#

set -e

long_opts=admin-kubeconfig:,metrics-server-manifest:
script_name=$(basename "$0")

admin_kubeconfig=
metrics_server_manifest=

function opt_val() {
  opt="$1"
  if [[ "$opt" == =* ]]; then
    echo "${opt:1}"
  else
    echo "$opt"
  fi
}

function parse_args() {
  if [[ "$#" -eq 0 ]]; then
    echo "no args provided"
    exit 1
  fi
  local parsed
  parsed=$(getopt --options "" --longoptions $long_opts -n $script_name -- "$@")
  eval set -- "$parsed"
  while true; do
    case "$1" in
      --admin-kubeconfig)
        admin_kubeconfig=$(opt_val "$2")
        shift 2
        ;;
      --metrics-server-manifest)
        metrics_server_manifest=$(opt_val "$2")
        shift 2
        ;;
      --)
        shift
        break
        ;;
    esac
  done
}

parse_args "$@"

echo
echo "installing kubernetes-sigs/metrics-server"
kubectl --kubeconfig $admin_kubeconfig apply -f $metrics_server
