#!/usr/bin/env bash
#
# Creates a template VM the way the 'dtk' script does it.
#

echo TODO THESE HAVE TO BE REWORKED
exit 1

if [[ -z "$DTKBASE" ]]; then
  echo 'requires environment variable DTKBASE. E.g.: export DTKBASE=~/projects/desktop-kubernetes'
  exit 0
fi

if [[ "$#" -ne 4 ]] && [[ "$#" -ne 5 ]]; then
  echo "Usage:"
  echo "hack/scripts/do-create-template-vm --host-only-network 192.168.56 my-template-vm /sdb1/virtualboxvms --rocky"
  echo "...or..."
  echo "hack/scripts/do-create-template-vm --host-network-interface enp0s31f6 rke2-template /sdb1/virtualboxvms --rocky"
  echo "the --rocky switch is optional"
  exit 1
fi

HOSTONLY=
HNI=
ROCKY=0
for arg; do
  if [[ "$arg" == "--rocky" ]]; then
    ROCKY=1
  fi
  if [[ "$arg" == "--host-only-network" ]]; then
    shift
    HOSTONLY=$1
  fi
  if [[ "$arg" == "--host-network-interface" ]]; then
    shift
    HNI=$1
  fi
done

if ! type -f xec &>/dev/null; then
  function xec() { f=$(find $DTKBASE/scripts -name $1) && $f "${@:2}"; }
  export -f xec
fi

linux_iso_download=https://mirror.umd.edu/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-latest-dvd1.iso
linux_iso_path=$DTKBASE/binaries/CentOS-Stream-8-x86_64-latest-dvd1.iso
guest_additions_download=https://download.virtualbox.org/virtualbox/6.1.36/VBoxGuestAdditions_6.1.36.iso
guest_additions_path=$DTKBASE/binaries/VBoxGuestAdditions_6.1.36.iso

if [[ $ROCKY -eq 1 ]]; then
  linux_iso_download=https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.0-x86_64-dvd.iso
  linux_iso_path=$DTKBASE/binaries/Rocky-9.0-x86_64-dvd.iso
fi

if [[ ! -z "$HOSTONLY" ]]; then
  xec create-template-vm\
    --template-vmname=$2\
    --linux-iso-path=$linux_iso_path\
    --guest-additions-path=$guest_additions_path\
    --host-only-network=$HOSTONLY\
    --vboxdir=$3
elif [[ ! -z "$HNI" ]]; then
  xec create-template-vm\
    --template-vmname=$2\
    --linux-iso-path=$linux_iso_path\
    --guest-additions-path=$guest_additions_path\
    --host-network-interface=$HNI\
    --vboxdir=$3
else
  echo "couldn't parse args"
fi
