#!/usr/bin/env bash
#
# Imports images into the containerd cache. Looks in hard-coded path
# '/tmp/images'. First untars any .tgz files if they exist. This enables
# to bundle up many tar files into a single tgz. Then for each .tar file
# in the directory, imports the tarred image into the containerd cache.
#

image_path=/tmp/images

find $image_path -name '*.tgz' | while read tarball; do
  tar -zxvf $tarball -C $image_path
  rm -f $tarball
done

find $image_path -name '*.tar' | while read tarfile; do
  ctr -n k8s.io -a /run/containerd/containerd.sock image import $tarfile
  rm -f $tarfile
done
