apiVersion: v1
kind: Pod
metadata:
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    command:
    - /usr/local/bin/etcd
    - --advertise-client-urls=https://INTERNAL_IP:2379
    - --cert-file=/etc/etcd/kubernetes.pem
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://INTERNAL_IP:2380
    - --initial-cluster=ETCD_NAME=https://INTERNAL_IP:2380
    - --initial-cluster-state=new
    - --initial-cluster-token=etcd-cluster-0
    - --key-file=/etc/etcd/kubernetes-key.pem
    - --listen-client-urls=https://0.0.0.0:2379
    - --listen-metrics-urls=http://0.0.0.0:2381
    - --listen-peer-urls=https://0.0.0.0:2380
    - --logger=zap
    - --log-level=info
    - --log-outputs=stderr
    - --name=ETCD_NAME
    - --peer-cert-file=/etc/etcd/kubernetes.pem
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/etcd/kubernetes-key.pem
    - --peer-trusted-ca-file=/etc/etcd/ca.pem
    - --trusted-ca-file=/etc/etcd/ca.pem
    image: quay.io/coreos/etcd:ETCD_VER
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources: {}
    securityContext:
      privileged: false
    volumeMounts:
    - name: d1
      mountPath: /etc/etcd/
      readOnly: true
    - name: d2
      mountPath: /var/lib/etcd/
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: d1
    hostPath:
      path: /etc/etcd/
      type: DirectoryOrCreate
  - name: d2
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
