apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - name: kube-controller-manager
    command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --bind-address=0.0.0.0
    - --cluster-cidr=CLUSTER_CIDR
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/var/lib/kubernetes/ca.pem
    - --cluster-signing-key-file=/var/lib/kubernetes/ca-key.pem
    - --kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig
    - --leader-elect=true
    - --root-ca-file=/var/lib/kubernetes/ca.pem
    - --service-account-private-key-file=/var/lib/kubernetes/service-account-key.pem
    - --service-cluster-ip-range=10.32.0.0/24
    - --use-service-account-credentials=true
    - --authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
    - --v=2
    image: registry.k8s.io/kube-controller-manager:K8S_VER
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 200m
    securityContext:
      privileged: false
    volumeMounts:
    - name: d1
      mountPath: /var/lib/kubernetes/
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: d1
    hostPath:
      path: /var/lib/kubernetes/
      type: DirectoryOrCreate
