apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-proxy
    tier: control-plane
  name: kube-proxy
  namespace: kube-system
spec:
  containers:
  - name: kube-proxy
    command:
    - /usr/local/bin/kube-proxy
    - --config=/var/lib/kube-proxy/kube-proxy-config.yaml
    env:
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    image: k8s.gcr.io/kube-proxy:v1.25.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
    securityContext:
      privileged: true
    volumeMounts:
    - name: d1
      mountPath: /var/lib/kube-proxy/
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: d1
    hostPath:
      path: /var/lib/kube-proxy/
      type: DirectoryOrCreate
